MARLEY (Model of Argon Reaction Low Energy Yields): marley::BackshiftedFermiGasModel Class Reference
marley::BackshiftedFermiGasModel Class Reference
Implementation of the back-shifted Fermi gas nuclear level density model.
#include <BackshiftedFermiGasModel.hh>
Public Member Functions
BackshiftedFermiGasModel (int Z, int A)
virtual double level_density (double Ex) override
virtual double level_density (double Ex, int two_J) override
virtual double level_density (double Ex, int two_J, marley::Parity Pi) override
Protected Member Functions
double compute_sigma_F2 (double Ex, double a)
Helper function used when evaluating the spin cutoff parameter.
Protected Attributes
int A_
mass number for this nuclide
double a_tilde_
asymptotic level density parameter (MeV -1)
double Delta_BFM_
excitation energy shift (MeV)
double delta_W_
shell correction energy (MeV)
double gamma_
damping parameter (MeV -1)
double sigma_
spin cut-off parameter
double sigma_d_global_
global fit for discrete-region spin cut-off parameter
double Sn_
neutron separation energy (MeV)
int Z_
atomic number for this nuclide
Detailed Description
Implementation of the back-shifted Fermi gas nuclear level density model.
Level density parameters used in this class are based on the global fits originally performed in A. J. Koning, et al., Nucl. Phys. A810 (2008) pp. 13-76. In addition to being used in MARLEY, this model has been adopted as one of the available options in the RIPL-3 data library and the TALYS nuclear code.
Definition at line 31 of file BackshiftedFermiGasModel.hh.
Constructor & Destructor Documentation
BackshiftedFermiGasModel()
marley::BackshiftedFermiGasModel::BackshiftedFermiGasModel (int Z, int A)
Create a back-shifted Fermi gas model object for a specific nuclide. This constructor will use global fits to initialize all level density parameters.
Parameters
Z atomic number of the desired nuclide
A mass number of the desired nuclide
Todo:
Add other constructors to the BackshiftedFermiGasModel class to allow the user to set the level density parameters based on local fits
Definition at line 23 of file BackshiftedFermiGasModel.cc.
   : Z_(Z), A_(A)
 {
   int N = A_ - Z_;
   double A_third = std::pow(A_, 1.0/3.0);
   // Parameters from global level density fit
   static constexpr double alpha = 0.0722396; // MeV^(-1)
   static constexpr double beta = 0.195267; // MeV^(-1)
   static constexpr double gamma_1 = 0.410289; // MeV(-1)
   static constexpr double delta_global = 0.173015; // MeV
   // Asymptotic level density parameter
   a_tilde_ = alpha*A_ + beta*std::pow(A_third, 2);
   // Damping parameter
   gamma_ = gamma_1 / A_third;
   const marley::MassTable& mt = marley::MassTable::Instance();
   // Shell correction energy
   delta_W_ = mt.get_mass_excess(Z_, A_)
     - mt.liquid_drop_model_mass_excess(Z_, A_);
   // Energy shift
   Delta_BFM_ = delta_global;
   bool z_odd = Z % 2;
   bool n_odd = N % 2;
   // There will be no change to the energy shift if the nucleus is odd-even
   if (z_odd && n_odd) Delta_BFM_ += -12/std::sqrt(A_);
   else if (!z_odd && !n_odd) Delta_BFM_ += 12/std::sqrt(A_);
   // Spin cut-off parameter
   sigma_d_global_ = 0.83*std::pow(A_, 0.26);
   Sn_ = mt.get_fragment_separation_energy(Z_, A_, marley_utils::NEUTRON);
 }
References A_, a_tilde_, Delta_BFM_, delta_W_, gamma_, marley::MassTable::get_fragment_separation_energy(), marley::MassTable::get_mass_excess(), marley::MassTable::Instance(), marley::MassTable::liquid_drop_model_mass_excess(), sigma_d_global_, Sn_, and Z_.
Member Function Documentation
level_density() [1/3]
double marley::BackshiftedFermiGasModel::level_density (double Ex) override virtual
Nuclear level density \(\rho(E_x) \) including all spins and parities.
Parameters
Ex Excitation energy in MeV
Returns
Level density in MeV -1
Note
Calls to this function update the spin cut-off parameter sigma_
Todo:
Replace Ed here with database of local fits taken from RIPL-3 or TALYS
Todo:
Reconsider method used for handling spin cut-off parameter calculation for U <= Ed.
Implements marley::LevelDensityModel.
Definition at line 77 of file BackshiftedFermiGasModel.cc.
{
   // Effective excitation energy
   double U = Ex - Delta_BFM_;
   // Level density parameter
   double a;
   if (U <= 0) { // Equivalently, Ex <= Delta_BFM_
     // Use first-order Taylor expansion for small energies
     a = a_tilde_ * (1 + gamma_ * delta_W_);
   }
   else {
     a = a_tilde_ * (1 + (delta_W_ / U) * (1 - std::exp(-gamma_ * U)));
   }
   const double Ed = 0.;
   // Compute the spin cut-off parameter sigma_
   // To avoid numerical problems, we will always use the discrete spin cutoff
   // parameter for U <= Ed.
   // The TALYS manual suggests using this for Ex <= Ed, but this isn't a huge
   // change. The actual TALYS code may make this same choice.
   if (U <= Ed) sigma_ = sigma_d_global_;
   else {
     if (Ex >= Sn_) {
       double sigma_F2 = compute_sigma_F2(Ex, a);
       sigma_ = std::sqrt(sigma_F2);
     }
     else {
       // sigma_F2 evaluated for Ex == Sn for the linear interpolation
       double sigma_F2_Sn = compute_sigma_F2(Sn_, a);
       // Ed < Ex < Sn_
       double sigma_d2 = std::pow(sigma_d_global_, 2);
       sigma_ = std::sqrt(sigma_d2 + (Ex - Ed)
         * (sigma_F2_Sn - sigma_d2) / (Sn_ - Ed));
     }
   }
   // For very small excitation energies, take the limit of the total
   // level density as U -> 0 to prevent numerical issues.
   if (U <= 0) {
     static const double exp1 = std::exp(1);
     return exp1 * a / (12 * sigma_);
   }
   double aU = a * U;
   double sqrt_aU = std::sqrt(aU);
   return std::pow(12 * sigma_ * (std::sqrt(2 * sqrt_aU)*U*std::exp(-2 * sqrt_aU)
     + std::exp(-aU - 1)/a), -1);
 }
level_density() [2/3]
double marley::BackshiftedFermiGasModel::level_density (double Ex, int two_J) override virtual
Level density \(\rho(E_x, J) \) for a specific nuclear spin.
Parameters
Ex Excitation energy in MeV
two_J Two times the nuclear spin
Returns
Level density in MeV -1
Implements marley::LevelDensityModel.
Definition at line 67 of file BackshiftedFermiGasModel.cc.
{
   double rho = level_density(Ex);
   // Spin-cutoff parameter sigma_ is updated by previous call to
   // this->level_density(Ex)
   double two_sigma2 = 2 * std::pow(sigma_, 2);
   return ((two_J + 1) / two_sigma2) * std::exp(-0.25 * std::pow(two_J + 1, 2)
     / two_sigma2) * rho;
 }
level_density() [3/3]
double marley::BackshiftedFermiGasModel::level_density (double Ex, int two_J, marley::Parity Pi) override virtual
Level density \(\rho(E_x, J, \Pi) \) for a specific nuclear spin and parity.
Parameters
Ex Excitation energy in MeV
two_J Two times the nuclear spin
Pi The nuclear parity
Returns
Level density in MeV -1
The current implementation assumes parity equipartition.
Implements marley::LevelDensityModel.
Definition at line 61 of file BackshiftedFermiGasModel.cc.
 {
   return 0.5 * level_density(Ex, two_J);
 }
The documentation for this class was generated from the following files:
/home/sjg/GENIE/marley/include/marley/BackshiftedFermiGasModel.hh
/home/sjg/GENIE/marley/src/BackshiftedFermiGasModel.cc