MARLEY (Model of Argon Reaction Low Energy Yields): marley::Generator Class Reference
marley::Generator Class Reference
The MARLEY Event generator.
#include <Generator.hh>
Public Member Functions
Generator ()
Create a Generator using default settings.
void add_reaction (std::unique_ptr< marley::Reaction > reaction)
Take ownership of a new Reaction.
void clear_reactions ()
Clear the vector of Reaction objects owned by this Generator.
marley::Event create_event ()
Create an Event using the NeutrinoSource, Target, Reaction, and StructureDatabase objects owned by this Generator.
marley::Event create_event (int pdg_a, double KEa, int pdg_atom, const std::array< double, 3 > &dir_vec)
Creates an event object for a fixed projectile species, kinetic energy, and atomic target.
double E_pdf (double E)
Probability density function that describes the distribution of reacting neutrino energies.
double flux_averaged_total_xs () const
Computes the flux-averaged total cross section for all enabled neutrino reactions, taking target atom fractions into account as appropriate.
const std::vector< std::unique_ptr< marley::Reaction > > & get_reactions () const
Get a const reference to the vector of Reaction objects owned by this Generator.
marley::ProjectileDirectionRotator & get_rotator ()
Provides access to the owned ProjectileDirectionRotator.
uint_fast64_t get_seed () const
Get the seed used to initialize this Generator.
const marley::NeutrinoSource & get_source () const
Get a const reference to the NeutrinoSource owned by this Generator.
std::string get_state_string () const
Get a string that represents the current internal state of this Generator.
marley::StructureDatabase & get_structure_db ()
Get a reference to the StructureDatabase owned by this Generator.
const marley::Target & get_target () const
Get a const reference to the Target owned by this Generator.
double inverse_transform_sample (const marley::ChebyshevInterpolatingFunction &cdf, double xmin, double xmax, double bisection_tolerance=1e-12)
Sample from a given 1D cumulative density function cdf(x) on the interval [xmin, xmax] using bisection.
double inverse_transform_sample (const std::function< double(double)> &f, double xmin, double xmax, double bisection_tolerance=1e-12)
Sample from a given 1D probability density function f(x) on the interval [xmin, xmax] using an inverse transform technique.
const std::array< double, 3 > & neutrino_direction ()
Gets the direction of the incident neutrinos that is used when generating events.
double rejection_sample (const std::function< double(double)> &f, double xmin, double xmax, double &fmax, double safety_factor=1.01, double max_search_tolerance=DEFAULT_REJECTION_SAMPLING_TOLERANCE_)
Sample from a given 1D probability density function f(x) on the interval [xmin, xmax] using a simple rejection method.
void reseed (uint_fast64_t seed)
Reseeds the Generator.
template<class RandomNumberDistribution >
auto sample_from_distribution (RandomNumberDistribution &rnd) -> decltype(std::declval< RandomNumberDistribution & >().operator()(std::declval< std::mt19937_64 & >()))
Sample from an arbitrary probability distribution (defined here as any object that implements an operator()(std::mt19937_64&) function) @detail This template function is based on https://stackoverflow.com/a/9154394/4081973.
template<class RandomNumberDistribution , typename ParamType >
auto sample_from_distribution (RandomNumberDistribution &rnd, const ParamType &params) -> decltype(std::declval< RandomNumberDistribution & >().operator()(std::declval< std::mt19937_64 & >(), std::declval< const ParamType & >()))
Sample from an arbitrary probability distribution (defined here as any object that implements an operator()(std::mt19937_64&, const ParamType&) function) using the parameters params.
marley::Reaction & sample_reaction (double &E)
Sample a Reaction and an energy for the reacting neutrino.
void seed_using_state_string (const std::string &state_string)
Use a string to set this Generator's internal state.
void set_do_deexcitations (bool do_them)
Sets the value of the do_deexcitations flag.
void set_neutrino_direction (const std::array< double, 3 > &dir_vec)
Sets the direction of the incident neutrinos to use when generating events.
void set_source (std::unique_ptr< marley::NeutrinoSource > source)
Take ownership of a new NeutrinoSource, replacing any existing source owned by this Generator.
void set_target (std::unique_ptr< marley::Target > target)
Take ownership of a new Target, replacing any existing target owned by this Generator.
void set_weight_flux (bool should_we_weight)
Sets the value of the weight_flux flag.
double total_xs (int pdg_a, double KEa) const
Computes the abundance-weighted total cross section at fixed energy for all configured reactions.
double total_xs (int pdg_a, double KEa, int pdg_atom) const
Computes the total cross section at fixed energy for all configured reactions involving a particular target atom.
double uniform_random_double (double min, double max, bool inclusive)
Sample a random number uniformly on either [min, max) or [min, max].
Detailed Description
The MARLEY Event generator.
Definition at line 42 of file Generator.hh.
Member Function Documentation
add_reaction()
void marley::Generator::add_reaction (std::unique_ptr< marley::Reaction > reaction)
Take ownership of a new Reaction.
Parameters
reaction A pointer to the new Reaction to use
Definition at line 406 of file Generator.cc.
 {
   // If we're passed a nullptr, then don't bother to do anything
   if ( reaction ) {
     // Transfer ownership to a new unique_ptr in the reactions vector, leaving
     // the original empty
     reactions_.push_back( std::move(reaction) );
     // Add a new entry in the reaction cross sections vector
     total_xs_values_.push_back( 0. );
     // TODO: consider adding a check to see whether source_ is non-null.
     // Right now, this shouldn't be possible, but an explicit check might
     // be good.
     // Update the neutrino energy probability density function by including the
     // cross section for the new reaction
     normalize_E_pdf();
   }
 }
create_event()
marley::Event marley::Generator::create_event (int pdg_a, double KEa, int pdg_atom, const std::array< double, 3 > & dir_vec)
Creates an event object for a fixed projectile species, kinetic energy, and atomic target.
If no energetically-accessible reaction is available for the given input parameters, then a marley::Error will be thrown.
Note
This function is not used as part of the normal MARLEY workflow. It serves as part of an API that enables MARLEY to be interfaced with an external flux driver.
Parameters
pdg_a The PDG code for the projectile
KEa The kinetic energy of the projectile (MeV)
pdg_atom The nuclear PDG code for the atomic target
dir_vec Direction three-vector of the projectile
Definition at line 593 of file Generator.cc.
 {
   // (1) Sample a reaction mode from all configured reactions that can handle
   // the given initial-state parameters
   std::vector<size_t> indices;
   std::vector<double> xsecs;
   double tot_xsec = this->total_xs( pdg_a, KEa, pdg_atom, &indices, &xsecs );
   if ( xsecs.empty() || tot_xsec <= 0. ) throw marley::Error(
     "Cannot create an event for a projectile with kinetic energy = "
     + std::to_string(KEa) + " MeV and PDG code " + std::to_string(pdg_a)
     + " striking an atom with PDG code " + std::to_string(pdg_atom)
     + ". The total cross section vanishes for all configured reactions" );
   // The total cross section values and indices in the full reactions_ vector
   // have already been loaded into temporary vectors, so we can immediately use
   // those to sample a reaction using a discrete distribution.
   std::discrete_distribution<size_t> react_dist( xsecs.begin(), xsecs.end() );
   size_t sampled_index = react_dist( rand_gen_ );
   auto& r = reactions_.at( indices.at(sampled_index) );
   // (2) Create the prompt two-two scattering event using the sampled reaction
   // object
   marley::Event ev = r->create_event( pdg_a, KEa, *this );
   // Do the usual post-processing
   // (3) If needed, de-excite the final-state residue
   if ( do_deexcitations_ ) {
     marley::NucleusDecayer nd;
     nd.process_event( ev, *this );
   }
   // (4) If needed, rotate the event to match the desired projectile direction
   // Set the incident neutrino direction for this event
   static marley::ProjectileDirectionRotator my_rotator;
   my_rotator.set_projectile_direction( dir_vec );
   // Rotate the coordinate system of the event if needed
   my_rotator.process_event( ev, *this );
   // Return the completed event object
   return ev;
 }
References marley::ProjectileDirectionRotator::process_event(), and marley::NucleusDecayer::process_event().
E_pdf()
double marley::Generator::E_pdf (double E)
Probability density function that describes the distribution of reacting neutrino energies.
This function computes the cross-section weighted neutrino flux (normalized to unity between source_->E_min and source_->E_max) including cross-section contributions from all Reactions owned by this Generator. For the distribution of incident neutrino energies, use marley::NeutrinoSource::pdf()
Parameters
E Total energy of the reacting neutrino
Returns
Probability density (MeV -1)
Definition at line 267 of file Generator.cc.
{
   // Initialize the return value to zero
   double pdf = 0.;
   // Sum all of the reaction total cross sections, saving
   // each individual value along the way. Take weighting
   // by atom fraction in the target material into account.
   for ( size_t j = 0, s = reactions_.size(); j < s; ++j ) {
     // Get the current reaction
     const auto& react = reactions_.at( j );
     // Compute the total cross section for the current reaction for a single
     // target atom
     double tot_xs = react->total_xs( source_->get_pid(), E );
     // If the target_ member has not been initialized, don't bother doing any
     // weighting by atom fraction (equivalent to a weight of unity for all
     // target atoms)
     if ( target_ ) {
       // If it has been configured, then apply the appropriate atom fraction
       // weight from the target as appropriate.
       tot_xs *= target_->atom_fraction( react->atomic_target() );
     }
     // Cache the atom-fraction-weighted total cross section for sampling a
     // reaction mode later
     total_xs_values_.at( j ) = tot_xs;
     // Add the weighted total cross section value to the total
     pdf += tot_xs;
   }
   // Normally, we want to fold the flux with the reaction cross section(s)
   // in order to obtain the distribution of reacting neutrino energies
   if ( weight_flux_ ) {
     // Multiply the total cross section by the neutrino spectrum
     // from the source object to get the (unnormalized) PDF
     // for sampling reacting neutrino energies.
     pdf *= source_->pdf(E);
   }
   else {
     // If the user has specifically requested it, don't weight the
     // energy PDF by the cross section(s), as long as at least one of them
     // is non-vanishing
     if ( pdf <= 0. ) return 0.;
     pdf = source_->pdf(E);
   }
   //  Divide by the normalization factor (computed when this source
   //  was made available to the Generator) to obtain the normalized PDF.
   return pdf / norm_;
 }
flux_averaged_total_xs()
double marley::Generator::flux_averaged_total_xs () const
Computes the flux-averaged total cross section for all enabled neutrino reactions, taking target atom fractions into account as appropriate.
If flux weighting is disabled (via a call to set_weight_flux()) then this function will return zero
Returns
Total cross section (MeV -2)
Definition at line 513 of file Generator.cc.
{
   // If we've disabled weighting the neutrino energy PDF
   // by the total cross section, just return zero
   if ( !weight_flux_ ) return 0.;
   double avg_total_xs = 0.;
   // For a monoenergetic source, don't bother to do the full
   // integral
   double Emin = source_->get_Emin();
   double Emax = source_->get_Emax();
   if ( Emin == Emax ) {
     avg_total_xs = norm_ / source_->pdf( Emin );
   }
   else {
     double source_norm = marley_utils::num_integrate(
       [this](double Ev) -> double { return this->source_->pdf(Ev); },
       Emin, Emax);
     // Use the precomputed integral of the reacting neutrino energy PDF
     avg_total_xs = norm_ / source_norm;
   }
   return avg_total_xs;
 }
Referenced by marley::TextOutputFile::write_generator_state().
get_source()
const marley::NeutrinoSource & marley::Generator::get_source () const
Get a const reference to the NeutrinoSource owned by this Generator.
Throws a marley::Error if this Generator does not own a NeutrinoSource object.
Definition at line 376 of file Generator.cc.
{
   if ( source_ ) return *source_;
   else throw marley::Error( "Error in marley::Generator::get_source()."
     " The member variable source_ == nullptr." );
 }
get_target()
const marley::Target & marley::Generator::get_target () const
Get a const reference to the Target owned by this Generator.
Throws a marley::Error if this Generator does not own a Target object.
Definition at line 382 of file Generator.cc.
{
   if ( target_ ) return *target_;
   else throw marley::Error( "Error in marley::Generator::get_target()."
     " The member variable target_ == nullptr." );
 }
inverse_transform_sample() [1/2]
double marley::Generator::inverse_transform_sample (const marley::ChebyshevInterpolatingFunction & cdf, double xmin, double xmax, double bisection_tolerance = 1e-12)
Sample from a given 1D cumulative density function cdf(x) on the interval [xmin, xmax] using bisection.
Parameters
cdf Cumulative density function to use for sampling
xmin Lower bound of the sampling interval
xmax Upper bound of the sampling interval
Returns
Sampled value of x
Definition at line 478 of file Generator.cc.
 {
   // Sample a probability value uniformly on [0, 1]
   double prob = uniform_random_double(0., 1., true);
   // If we chose an endpoint, we're done, so just return the appropriate one
   if ( prob == 0. ) return xmin;
   else if ( prob == 1. ) return xmax;
   // A properly normalized CDF should evaluate to unity at x = xmax. We enforce
   // this here so that the user doesn't have to do it in advance.
   double norm = cdf.evaluate( xmax );
   // Find the x value corresponding to the sampled probability via bisection
   // (slow but robust)
   double a = xmin;
   double b = xmax;
   while ( (b - a) > bisection_tolerance ) {
     double midpoint = (a + b) / 2.;
     double mid_cdf = cdf.evaluate( midpoint ) / norm;
     // If the CDF at the midpoint exactly matches our sampled
     // probability, we're done. Just return the midpoint.
     if ( mid_cdf == prob ) return midpoint;
     // Otherwise, shrink the bisection interval and try again
     else if ( mid_cdf > prob ) b = midpoint;
     else a = midpoint; // mid_cdf < prob
   }
   // Return the midpoint of the bisection interval as our sampled x value
   double x = (a + b) / 2.;
   return x;
 }
References marley::ChebyshevInterpolatingFunction::evaluate().
inverse_transform_sample() [2/2]
double marley::Generator::inverse_transform_sample (const std::function< double(double)> & f, double xmin, double xmax, double bisection_tolerance = 1e-12)
Sample from a given 1D probability density function f(x) on the interval [xmin, xmax] using an inverse transform technique.
Parameters
f Probability density function to use for sampling
xmin Lower bound of the sampling interval
xmax Upper bound of the sampling interval
Returns
Sampled value of x
Todo:
Remove hard-coded number of points here
Definition at line 462 of file Generator.cc.
 {
   // Build an approximate CDF corresponding to the integral of the input PDF.
   // Use a polynomial approximant at Chebyshev points to do it.
   marley::ChebyshevInterpolatingFunction func(f, xmin, xmax,
     DEFAULT_N_CHEBYSHEV);
   auto cdf = func.cdf();
   // Now that we have a CDF to use for sampling, delegate the rest of the
   // action to the overloaded version of this function.
   return this->inverse_transform_sample(cdf, xmin, xmax, bisection_tolerance);
 }
rejection_sample()
double marley::Generator::rejection_sample (const std::function< double(double)> & f, double xmin, double xmax, double & fmax, double safety_factor = 1.01, double max_search_tolerance = DEFAULT_REJECTION_SAMPLING_TOLERANCE_)
Sample from a given 1D probability density function f(x) on the interval [xmin, xmax] using a simple rejection method.
Parameters
f Probability density function to use for sampling
xmin Lower bound of the sampling interval
xmax Upper bound of the sampling interval
max_search_tolerance Tolerance to use when finding the maximum of f(x) using Brent's method
Returns
Sampled value of x
The rejection method used by this function consists of the following steps:
Find the maximum of the function f(x) on [xmin, xmax]
Sample an x value uniformly over f(x)'s domain
Sample a y value uniformly over [0, max(f(x))]
If y <= f(x), accept the sampled x value
If y > f(x), reject the sampled x value, and return to step 2 to try again
Note that f(x) does not need to be normalized, but its range must be nonnegative. In the first step, an iterative method (Brent's method) is used to find the maximum of f(x). The iterations will continue until two successive iterations agree within max_search_tolerance on the location of the maximum of f(x). To avoid problems with functions that yield double values that are small compared to a typical value of max_search_tolerance (say, max_search_tolerance = 1e-8, while many neutrino cross sections of interest for MARLEY are less than 1e-40 cm^2), MARLEY normalizes all probability density functions to unity before using rejection sampling.
Definition at line 219 of file Generator.cc.
 {
   // If we were passed the value marley_utils::UNKNOWN_MAX for fmax, then this
   // signals that we need to search for the function maximum ourselves.
   // Otherwise, we'll assume that the value passed over is good.
   if ( fmax == marley_utils::UNKNOWN_MAX  ) {
     // This variable will be loaded with the value of x
     // that corresponds to the maximum of f(x).
     // We don't actually use this, but currently it's
     // a required parameter of marley_utils::maximize
     double x_at_max;
     // Maximize the function and multiply by a safety factor just
     // in case we didn't quite find the exact peak
     fmax = marley_utils::maximize(f, xmin, xmax, max_search_tolerance,
       x_at_max) * safety_factor;
   }
   double x, y, val;
   do {
     // Sample x value uniformly from [xmin, xmax]
     x = uniform_random_double(xmin, xmax, true);
     // Sample y uniformly from [0, fmax]
     y = uniform_random_double(0, fmax, true);
     val = f(x);
     if ( val > fmax ) {
       MARLEY_LOG_WARNING() << "PDF value f(x) = "
       << val << " at x = " << x << " exceeded the estimated maximum"
       << " fmax = " << fmax << " during rejection sampling.";
       fmax = val * safety_factor;
       MARLEY_LOG_WARNING() << "A new estimate fmax = " << val * safety_factor
         << " will now be adopted.";
     }
   }
   // Keep sampling until you get a y value less than f(x)
   // (the probability density function evaluated at the sampled value of x)
   while ( y > val );
   return x;
 }
Referenced by marley::ElectronReaction::create_event(), marley::NuclearReaction::sample_cos_theta_c_cm(), and marley::NeutrinoSource::sample_incident_neutrino().
sample_reaction()
marley::Reaction & marley::Generator::sample_reaction (double & E)
Sample a Reaction and an energy for the reacting neutrino.
Parameters
[out] E Total energy of the neutrino undergoing the reaction
Returns
Reference to the sampled Reaction owned by this Generator
Definition at line 322 of file Generator.cc.
{
   if ( reactions_.empty() ) throw marley::Error("Cannot sample"
     " a reaction in marley::Generator::sample_reaction(). The vector of"
     " marley::Reaction objects owned by this generator is empty.");
   // Store the "old" value of E_pdf_max_, i.e., the one we had before calling
   // rejection_sample(). This will be used to check for problems.
   double old_max = E_pdf_max_;
   // TODO: protect against source_ changing E_min or E_max after you compute
   // the normalization factor norm_ in marley::Generator::init()
   E = rejection_sample([this](double E_nu)
     -> double { return this->E_pdf(E_nu); }, source_->get_Emin(),
     source_->get_Emax(), E_pdf_max_);
   // If the value of max changed after the call to rejection_sample() and the
   // old value wasn't UNKNOWN_MAX, then the rejection sampling routine must
   // have encountered a PDF value that was larger than our estimated maximum.
   // Alert the user about this and advise them to change the configuration
   // appropriately to avoid a biased reacting neutrino energy distribution.
   static bool issued_long_error_message = false;
   if ( old_max != marley_utils::UNKNOWN_MAX
     && old_max != E_pdf_max_ )
   {
     if ( !issued_long_error_message ) {
       MARLEY_LOG_ERROR() << "Estimation of the maximum PDF value failed when"
         << " using a rejection method to sample reacting neutrino energies.\n"
         << "This may occur when, e.g., an incident neutrino flux"
         << " is used that includes multiple sharp peaks.\n"
         << "To avoid biasing the energy distribution, please rerun the simulation"
         << " after adding the following line to the MARLEY job configuration"
         << " file:\n"
         << "    energy_pdf_max: " << E_pdf_max_ << ",\n"
         << "If this error message persists after raising energy_pdf_max to a"
         << " relatively high value, please contact the MARLEY developers for"
         << " troubleshooting help.";
       issued_long_error_message = true;
     }
     else {
       MARLEY_LOG_ERROR() << "The maximum PDF value for sampling reacting neutrino"
        << " energies was exceeded again. The new estimated maximum is"
        << "\n    energy_pdf_max: " << E_pdf_max_ << ',';
     }
   }
   // The atom-fraction-weighted total cross section values have already been
   // updated by the final call to E_pdf() during rejection sampling, so we can
   // now sample a reaction type using our discrete distribution object.
   std::discrete_distribution<size_t>::param_type
     params( total_xs_values_.begin(), total_xs_values_.end() );
   size_t r_index = r_index_dist_( rand_gen_, params );
   return *reactions_.at( r_index );
 }
seed_using_state_string()
void marley::Generator::seed_using_state_string (const std::string & state_string)
Use a string to set this Generator's internal state.
This function is typically used to restore a Generator to a state saved using get_state_string().
Definition at line 91 of file Generator.cc.
 {
   // TODO: add error handling here (check that state_string is valid)
   std::stringstream strstr( state_string );
   strstr >> rand_gen_;
 }
set_do_deexcitations()
void marley::Generator::set_do_deexcitations (bool do_them) inline
Sets the value of the do_deexcitations flag.
This should almost always be true. Use only if you know what you are doing.
Definition at line 391 of file Generator.hh.
     { do_deexcitations_ = do_them; }
set_neutrino_direction()
void marley::Generator::set_neutrino_direction (const std::array< double, 3 > & dir_vec)
Sets the direction of the incident neutrinos to use when generating events.
Parameters
dir_vec Vector that points in the direction of the incident neutrinos
Note
The dir_vec passed to this function does not need to be normalized, but it must have at least one nonzero element or a marley::Error will be thrown.
Definition at line 442 of file Generator.cc.
 {
   rotator_.set_projectile_direction( dir_vec );
   const auto& normalized_dir_vec = rotator_.projectile_direction();
   // Print a log message announcing the change of direction
   std::string dir_msg("Incident neutrino direction: (");
   for ( size_t i = 0; i < 3; ++i ) {
     dir_msg += std::to_string( normalized_dir_vec[i] );
     if ( i < 2 ) dir_msg += ", ";
   }
   MARLEY_LOG_INFO() << dir_msg << ')';
 }
set_source()
void marley::Generator::set_source (std::unique_ptr< marley::NeutrinoSource > source)
Take ownership of a new NeutrinoSource, replacing any existing source owned by this Generator.
Parameters
source A pointer to the new NeutrinoSource to use
Definition at line 388 of file Generator.cc.
 {
   // If we're passed a nullptr, then don't bother to do anything
   if ( source ) {
     // Transfer ownership of the neutrino source the generator, leaving
     // the std::unique_ptr passed to this function null afterwards.
     source_.reset( source.release() );
     // Don't bother to renormalize if there are no reactions defined yet
     if ( reactions_.empty() ) return;
     // Update the neutrino energy probability density function based on the
     // new source spectrum
     this->normalize_E_pdf();
   }
 }
set_target()
void marley::Generator::set_target (std::unique_ptr< marley::Target > target)
Take ownership of a new Target, replacing any existing target owned by this Generator.
Parameters
source A pointer to the new Target to use
Definition at line 538 of file Generator.cc.
 {
   // If we're passed a nullptr, then don't bother to do anything
   if ( target ) {
     // Transfer ownership of the neutrino target to the generator, leaving
     // the std::unique_ptr passed to this function null afterwards.
     target_.reset( target.release() );
     // Don't bother to renormalize if there are no reactions defined yet
     if ( reactions_.empty() ) return;
     // Update the neutrino energy probability density function based on the
     // new target composition
     this->normalize_E_pdf();
   }
 }
set_weight_flux()
void marley::Generator::set_weight_flux (bool should_we_weight)
Sets the value of the weight_flux flag.
This is potentially dangerous. Use only if you know what you are doing.
Definition at line 458 of file Generator.cc.
{
   weight_flux_ = should_we_weight;
 }
total_xs() [1/2]
double marley::Generator::total_xs (int pdg_a, double KEa) const
Computes the abundance-weighted total cross section at fixed energy for all configured reactions.
Atom fractions in the owned Target are used to perform the weighting by nuclide abundance
Note
This function is not used as part of the normal MARLEY workflow. It exposes the abundance-weighted total cross section for use by the mardumpxs command-line tool (see examples/executables/mardumpxs.cc)
Parameters
pdg_a The PDG code for the projectile
KEa The kinetic energy of the projectile (MeV)
Returns
Abundance-weighted total cross section (MeV -2 / atom)
Definition at line 641 of file Generator.cc.
{
   // Initialize the return value to zero
   double tot_xsec = 0.;
   // Sum all of the reaction total cross sections. Take weighting by atom
   // fraction in the target material into account.
   for ( const auto& react : reactions_ ) {
     // Compute the total cross section for the current reaction for a single
     // target atom
     double xsec = react->total_xs( pdg_a, KEa );
     // If the target_ member has not been initialized, don't bother doing any
     // weighting by atom fraction (equivalent to a weight of unity for all
     // target atoms)
     if ( target_ ) {
       // If it has been configured, then apply the appropriate atom fraction
       // weight from the target as appropriate.
       xsec *= target_->atom_fraction( react->atomic_target() );
     }
     // Add the weighted total cross section value to the total
     tot_xsec += xsec;
   }
   return tot_xsec;
 }
total_xs() [2/2]
double marley::Generator::total_xs (int pdg_a, double KEa, int pdg_atom) const
Computes the total cross section at fixed energy for all configured reactions involving a particular target atom.
Atom fractions in the owned Target are ignored by this function.
Note
This function is not used as part of the normal MARLEY workflow. It serves as part of an API that enables MARLEY to be interfaced with an external flux driver.
Parameters
pdg_a The PDG code for the projectile
KEa The kinetic energy of the projectile (MeV)
pdg_atom The nuclear PDG code for the atomic target
Returns
Total cross section (MeV -2 / atom)
Definition at line 555 of file Generator.cc.
 {
   return this->total_xs( pdg_a, KEa, pdg_atom, nullptr, nullptr );
 }
uniform_random_double()
double marley::Generator::uniform_random_double (double min, double max, bool inclusive)
Sample a random number uniformly on either [min, max) or [min, max].
Parameters
min Lower bound of the sampling interval
max Upper bound of the sampling interval
inclusive Whether the upper bound should be included (true) or excluded (false) from the possible sampling outcomes
Definition at line 173 of file Generator.cc.
 {
   // Defaults to sampling from [0,1). We will always
   // explicitly supply the upper and lower bounds to
   // this distribution, so we won't worry about the
   // default setting.
   static std::uniform_real_distribution<double> udist;
   double max_to_use;
   if ( inclusive ) { // sample from [min, max]
     // Find the double value that comes immediately after max. This allows us
     // to sample uniformly on [min, max] rather than [min,max). This trick
     // comes from http://tinyurl.com/n3ocg3p.
     max_to_use = std::nextafter( max, std::numeric_limits<double>::max() );
   }
   else { // sample from [min, max)
     max_to_use = max;
   }
   std::uniform_real_distribution<double>::param_type params( min, max_to_use );
   // Sample a random double from this distribution
   return udist( rand_gen_, params );
 }
Referenced by marley::ElectronReaction::create_event(), marley::NuclearReaction::create_event(), marley::DecayScheme::do_cascade(), and marley::ExitChannel::prepare_products().
The documentation for this class was generated from the following files:
/home/sjg/GENIE/marley/include/marley/Generator.hh
/home/sjg/GENIE/marley/src/Generator.cc