MARLEY (Model of Argon Reaction Low Energy Yields): marley::NucleusDecayer Class Reference
marley::NucleusDecayer Class Reference
EventProcessor that handles nuclear de-excitations.
#include <NucleusDecayer.hh>
Public Member Functions
virtual void process_event (marley::Event &event, marley::Generator &gen) override
Processes an input MARLEY Event object.
Detailed Description
EventProcessor that handles nuclear de-excitations.
Definition at line 23 of file NucleusDecayer.hh.
Member Function Documentation
process_event()
void marley::NucleusDecayer::process_event (marley::Event & ev, marley::Generator & gen) override virtual
Processes an input MARLEY Event object.
Parameters
[in,out] ev The Event object to be processed
[in] gen If needed, the Generator object to use during processing (e.g., for obtaining random numbers)
Todo:
Revisit this
Implements marley::EventProcessor.
Definition at line 46 of file NucleusDecayer.cc.
 {
   // Get the residue excitation energy from the event. These values represent
   // its state immediately following the initial two-two scattering reaction.
   double Ex = event.Ex();
   int twoJ = event.twoJ();
   marley::Parity P = event.parity();
   // If the initial two-two scatter left the residue in its ground state,
   // there's nothing for us to do. Just return without comment.
   if ( Ex == 0. ) return;
   // The excitation energy should be nonnegative. Complain if it's not.
   if ( Ex < 0. ) throw marley::Error("Negative excitation energy Ex = "
     + std::to_string(Ex) + " MeV encountered in marley::NucleusDecayer::"
     "deexcite_residue()");
   // To prevent accidental double application of the de-excitation cascade,
   // check that the residue mass is consistent with the excitation energy
   // stored in the event record (and thus was never decayed).
   const auto& mt = marley::MassTable::Instance();
   int initial_residue_pdg = event.residue().pdg_code();
   int qIon = event.residue().charge();
   // Check that the residue PDG code makes sense. If it's not a nucleus,
   // warn the user and refuse to do the cascade.
   if ( !marley_utils::is_ion(initial_residue_pdg) ) {
     MARLEY_LOG_WARNING() << "Unrecognized nuclear PDG code "
       << initial_residue_pdg << " encountered in marley::NucleusDecayer::"
       << "deexcite_residue(). The de-excitation cascade will be skipped";
     return;
   }
   double residue_mass = event.residue().mass();
   // Ground-state residue mass
   double gs_residue_mass = mt.get_atomic_mass( initial_residue_pdg )
     - qIon*mt.get_particle_mass( marley_utils::ELECTRON );
   double expected_residue_mass = gs_residue_mass + Ex;
   if ( std::abs(residue_mass - expected_residue_mass) > EX_TOLERANCE ) {
     if ( std::abs(residue_mass - gs_residue_mass) <= EX_TOLERANCE ) {
       MARLEY_LOG_WARNING() << "Encountered ground-state nuclear remnant"
         << " in marley::NucleusDecay::deexcite_residue(). The de-excitation"
         << " cascade has already been applied.";
       return;
     }
     // If we get here, then the residue is not in its ground state but also
     // not in the initial excited state given in the event record. Something
     // went wrong with a partial application of a de-excitation cascade.
     // Throw an error rather than trying to figure out how to do the right
     // thing.
     throw marley::Error("Partially de-excited nuclear remnant encountered"
         " in marley::NucleusDecay::deexcite_residue().");
   }
   // Decide whether we need to start the de-excitation cascade from a discrete
   // nuclear level or from the continuum. Do this by comparing the excitation
   // energy from the event record to the "unbound threshold" for the residue.
   // If we're above the unbound threshold, do a continuum decay. Also start
   // with a continuum decay if no discrete level data are available for the
   // residue.
   auto* ds = gen.get_structure_db().get_decay_scheme( initial_residue_pdg );
   double unbound_threshold = mt.unbound_threshold( initial_residue_pdg );
   // If Reaction::set_level_ptrs() changes, you'll want to change this too.
   // TODO: find a better way of keeping the two pieces of code in sync
   bool continuum = ( Ex > unbound_threshold ) || ( !ds );
   // Keep track of whether the cascade was started from the continuum
   // or not. If it was started from a discrete level, we'll double-check that
   // discrete level's excitation energy below.
   bool started_from_continuum = continuum;
   // Get a non-const reference to the nuclear residue. We'll use it to
   // update the event record during each step of the Hauser-Feshbach
   // cascade.
   marley::Particle& residue = event.residue();
   if ( continuum ) {
     // Dummy particles used for temporary storage of binary decay products
     // during the de-excitation cascade
     marley::Particle first, second;
     // The selected level is unbound, so handle its de-excitation using
     // the Hauser-Feshbach statistical model.
     while ( continuum && Ex > CONTINUUM_GS_CUTOFF ) {
       auto& sdb = gen.get_structure_db();
       marley::HauserFeshbachDecay hfd( residue, Ex, twoJ, P, sdb );
       MARLEY_LOG_DEBUG() << hfd;
       continuum = hfd.do_decay( Ex, twoJ, P, first, second, gen );
       MARLEY_LOG_DEBUG() << "Hauser-Feshbach decay to " << first.pdg_code()
         << " and " << second.pdg_code();
       MARLEY_LOG_DEBUG() << second.pdg_code() << " is at Ex = "
         << Ex << " MeV.";
       residue = second;
       event.add_final_particle( first );
     }
   }
   if ( !continuum ) {
     // Either the selected initial level was bound (so it will only decay via
     // gamma emission) or the Hauser-Feshbach decay process has now accessed a
     // bound level in the residual nucleus. In either case, use gamma-ray decay
     // scheme data to sample the de-excitation gammas and add them to this
     // event's final particle list.
     marley::DecayScheme* dec_scheme = gen.get_structure_db()
       .get_decay_scheme( residue.pdg_code() );
     // Start the gamma cascade from this discrete level
     marley::Level* lev = dec_scheme->get_pointer_to_closest_level( Ex );
     // If we get a null level pointer from the decay scheme, complain
     if ( !lev ) throw marley::Error("Null nuclear level pointer encountered"
       " in marley::NucleusDecayer::deexcite_residue()");
     // If we did not simulate any continuum decays before getting to this
     // point, then double-check that the excitation energy from the event
     // record and the initial level are consistent. If they're not, complain
     // by throwing an error.
     if ( !started_from_continuum ) {
       double Ex_level = lev->energy();
       if ( std::abs(Ex - Ex_level) > EX_TOLERANCE ) {
         throw marley::Error("Excitation energy mismatch encountered in"
           " marley::NucleusDecayer::deexcite_residue(). Event has Ex = "
           + std::to_string(Ex) + " MeV while the initial discrete level has "
           + std::to_string(Ex_level) + " MeV");
       }
     }
     dec_scheme->do_cascade( *lev, event, gen, residue.charge() );
   }
 }
References marley::Particle::charge(), marley::DecayScheme::do_cascade(), marley::HauserFeshbachDecay::do_decay(), marley::Level::energy(), marley::StructureDatabase::get_decay_scheme(), marley::DecayScheme::get_pointer_to_closest_level(), marley::Generator::get_structure_db(), marley::MassTable::Instance(), and marley::Particle::pdg_code().
Referenced by marley::Generator::create_event().
The documentation for this class was generated from the following files:
/home/sjg/GENIE/marley/include/marley/NucleusDecayer.hh
/home/sjg/GENIE/marley/src/NucleusDecayer.cc