MARLEY (Model of Argon Reaction Low Energy Yields): marley::DecayScheme Class Reference
marley::DecayScheme Class Reference
Discrete level and γ-ray data for a specific nuclide.
#include <DecayScheme.hh>
Public Types
enum class FileFormat { native , talys }
The FileFormat type is used to tell the DecayScheme class which format to assume when parsing a discrete level data file.
Public Member Functions
DecayScheme (int Z, int A)
Create a DecayScheme without any levels.
DecayScheme (int Z, int A, const std::string &filename, FileFormat format=FileFormat::talys)
Create a DecayScheme using discrete level data from a file.
int A () const
Get the mass number.
marley::Level & add_level (const marley::Level &level)
Add a level to the DecayScheme.
void do_cascade (marley::Level &initial_level, marley::Event &event, marley::Generator &gen, int qIon)
Simulates nuclear de-excitation via γ-ray emission(s)
const std::vector< std::unique_ptr< marley::Level > > & get_levels () const
Get a const reference to the vector that holds the Level objects.
marley::Level * get_pointer_to_closest_level (double E_level)
Gets a pointer to the Level in the DecayScheme whose excitation energy is closest to E_level.
int pdg () const
Returns the nuclear PDG code corresponding to Z and A.
void print (std::ostream &out=std::cout) const
Print this DecayScheme object to a std::ostream.
void print_latex_table (std::ostream &ostr=std::cout)
Print LaTeX source code that gives a tabular representation of the DecayScheme object.
void print_report (std::ostream &ostr=std::cout) const
Print a human-readable text representation of the DecayScheme object.
void read_from_stream (std::istream &in)
Use a std::istream to initialize this DecayScheme object, replacing any previous data.
int Z () const
Get the atomic number.
Protected Member Functions
size_t level_lower_bound_index (double Ex)
Get the index of the first level whose energy is not less than Ex.
Protected Attributes
int A_
Mass number.
std::vector< std::unique_ptr< marley::Level > > levels_
Level objects owned by this DecayScheme.
int Z_
Atomic number.
Detailed Description
Discrete level and γ-ray data for a specific nuclide.
Definition at line 30 of file DecayScheme.hh.
Member Enumeration Documentation
FileFormat
enum marley::DecayScheme::FileFormat strong
The FileFormat type is used to tell the DecayScheme class which format to assume when parsing a discrete level data file.
Currently, only discrete level data in MARLEY's native format (which may be read from a std::istream to initialize a marley::DecayScheme object via the >> operator) or in the format used by the TALYS nuclear code are allowed.
Definition at line 41 of file DecayScheme.hh.
 { native, talys };
Constructor & Destructor Documentation
DecayScheme() [1/2]
marley::DecayScheme::DecayScheme (int Z, int A)
Create a DecayScheme without any levels.
Parameters
Z Atomic number of the desired nuclide
A Mass number of the desired nuclide
Definition at line 143 of file DecayScheme.cc.
                                            : Z_(Z), A_(A)
 {
 }
DecayScheme() [2/2]
marley::DecayScheme::DecayScheme (int Z, int A, const std::string & filename, FileFormat format = FileFormat::talys)
Create a DecayScheme using discrete level data from a file.
Parameters
Z Atomic number of the desired nuclide
A Mass number of the desired nuclide
filename Name of the file containing the discrete level data
format FileFormat specifier that indicates which nuclear data format is used in the file
Definition at line 147 of file DecayScheme.cc.
                                   : Z_(Z), A_(A)
 {
   parse(filename, ff);
 }
Member Function Documentation
add_level()
marley::Level & marley::DecayScheme::add_level (const marley::Level & level)
Add a level to the DecayScheme.
Returns
A reference to the newly-added Level object
Definition at line 367 of file DecayScheme.cc.
 {
   // Compute the numerical index for where we will insert the new level
   size_t index = level_lower_bound_index(level.energy());
   // Insert the new level into the decay scheme
   levels_.insert(levels_.begin() + index,
     std::make_unique<marley::Level>(level));
   // Return a reference to the newly-added level
   return *levels_.at(index);
 }
References marley::Level::energy().
do_cascade()
void marley::DecayScheme::do_cascade (marley::Level & initial_level, marley::Event & event, marley::Generator & gen, int qIon)
Simulates nuclear de-excitation via γ-ray emission(s)
Gamma-rays will be randomly emitted until the nucleus reaches its ground state.
Parameters
[in] initial_level Reference to the first level that will de-excite via γ-ray emission
[in,out] event Reference to an Event object that will store the emitted γs
[in] gen Reference to the Generator to use for random sampling
qIon Net charge of the atom or ion whose nucleus is de-exciting
Definition at line 71 of file DecayScheme.cc.
 {
   MARLEY_LOG_DEBUG() << "Beginning gamma cascade at level with energy "
     << initial_level.energy() << " MeV";
   bool cascade_finished = false;
   marley::Level* p_current_level = &initial_level;
   const marley::MassTable& mt = marley::MassTable::Instance();
   while (!cascade_finished) {
     // Randomly select a gamma to produce
     const marley::Gamma* p_gamma = p_current_level->sample_gamma(gen);
     if (!p_gamma) {
       MARLEY_LOG_DEBUG() << "  this level does not have any gammas";
       cascade_finished = true;
     }
     else {
       p_current_level = p_gamma->end_level();
       if (!p_current_level) {
         throw marley::Error(std::string("This")
           + "gamma does not have an end level. Cannot continue cascade.");
       }
       MARLEY_LOG_DEBUG() << std::setprecision(15) << std::scientific
         << "  emitted gamma with energy "
         << p_gamma->energy() << " MeV. New level has energy "
         << p_current_level->energy() << " MeV.";
       MARLEY_LOG_DEBUG() << "gamma energy = " << p_gamma->energy();
       // Get the excitation energy of the end level. This will be added to
       // the ground state mass of the nucleus to determine its
       // post-gamma-emission mass.
       double Exf = p_current_level->energy();
       // Create new particle objects to represent the emitted gamma and
       // recoiling nucleus
       marley::Particle gamma(marley_utils::PHOTON, 0);
       int pdg = marley_utils::get_nucleus_pid(Z_, A_);
       marley::Particle nucleus(pdg, mt.get_atomic_mass(pdg)
         + Exf - qIon*mt.get_particle_mass(marley_utils::ELECTRON), qIon);
       // Sample a direction assuming that the gammas are emitted
       // isotropically in the nucleus's rest frame.
       // sample from [-1,1]
       double gamma_cos_theta = gen.uniform_random_double(-1, 1, true);
       // sample from [0,2*pi)
       double gamma_phi = gen.uniform_random_double(0, 2*marley_utils::pi,
         false);
       marley::Particle& residue = event.residue();
       // Determine the final energies and momenta for the recoiling nucleus and
       // emitted gamma ray. Store them in the final state particle objects.
       marley_kinematics::two_body_decay(residue, gamma, nucleus,
         gamma_cos_theta, gamma_phi);
       // Update the residue for this event to take into account changes from
       // gamma ray emission
       residue = nucleus;
       // Add the new gamma to the event
       event.add_final_particle(gamma);
     }
   }
   MARLEY_LOG_DEBUG() << "Finished gamma cascade at level with energy "
     << p_current_level->energy();
 }
References marley::Gamma::end_level(), marley::Gamma::energy(), marley::Level::energy(), marley::MassTable::get_atomic_mass(), marley::MassTable::get_particle_mass(), marley::MassTable::Instance(), marley::Level::sample_gamma(), and marley::Generator::uniform_random_double().
Referenced by marley::NucleusDecayer::process_event().
get_pointer_to_closest_level()
marley::Level * marley::DecayScheme::get_pointer_to_closest_level (double E_level)
Gets a pointer to the Level in the DecayScheme whose excitation energy is closest to E_level.
Parameters
E_level excitation energy (MeV)
Note
Returns nullptr if the DecayScheme doesn't own any Level objects
Definition at line 35 of file DecayScheme.cc.
 {
   // If this decay scheme doesn't own any levels, return nullptr immediately
   size_t num_levels = levels_.size();
   if (num_levels == 0) return nullptr;
   // Search for the level whose energy is closest to the given value of E_level
   size_t e_index = level_lower_bound_index(E_level);
   if (e_index == num_levels) {
     // The given energy is greater than every level energy in our decay scheme.
     // We will therefore assume that the desired level is the highest level.
     // Its index is given by one less than the number of elements in the sorted
     // vector, so subtract one from our previous result.
     --e_index;
   }
   else if (e_index > 0) {
     // If the calculated index does not correspond to the first element, we
     // still need to check which of the two levels found (one on each side) is
     // really the closest. Do so and reassign the index if needed.
     if (std::abs(E_level - levels_.at(e_index)->energy())
       > std::abs(E_level - levels_.at(e_index - 1)->energy()))
     {
       --e_index;
     }
   }
   // Return a pointer to the selected level object
   return levels_.at(e_index).get();
 }
References level_lower_bound_index(), and levels_.
Referenced by marley::NucleusDecayer::process_event().
level_lower_bound_index()
size_t marley::DecayScheme::level_lower_bound_index (double Ex) protected
Get the index of the first level whose energy is not less than Ex.
Parameters
Ex Excitation energy (MeV)
Note
Returns levels_.size() if all levels have energies below Ex
Definition at line 358 of file DecayScheme.cc.
{
   const auto E_begin = marley::Level::make_energy_iterator(levels_.cbegin());
   const auto E_end = marley::Level::make_energy_iterator(levels_.cend());
   const auto closest_E_iter = std::lower_bound(E_begin, E_end, Ex);
   return std::distance(E_begin, closest_E_iter);
 }
References marley::Level::make_energy_iterator().
Referenced by get_pointer_to_closest_level().
read_from_stream()
void marley::DecayScheme::read_from_stream (std::istream & in)
Use a std::istream to initialize this DecayScheme object, replacing any previous data.
The expected format for data in the std::istream is the same as the output format in DecayScheme::print()
Definition at line 404 of file DecayScheme.cc.
{
   levels_.clear();
   int num_levels;
   in >> Z_ >> A_ >> num_levels;
   // If we had trouble parsing the decay scheme header, then
   // just return the stream without doing anything else.
   if ( !in ) return;
   double energy, ri;
   int two_j, num_gammas, level_f_idx;
   marley::Parity pi;
   for ( int i = 0; i < num_levels; ++i ) {
     in >> energy >> two_j >> pi >> num_gammas;
     marley::Level& l = add_level( marley::Level(energy, two_j, pi) );
     for ( int j = 0; j < num_gammas; ++j ) {
       in >> energy >> ri >> level_f_idx;
       l.add_gamma( energy, ri, levels_.at(level_f_idx).get() );
     }
   }
 }
References marley::Level::add_gamma().
The documentation for this class was generated from the following files:
/home/sjg/GENIE/marley/include/marley/DecayScheme.hh
/home/sjg/GENIE/marley/src/DecayScheme.cc