MARLEY (Model of Argon Reaction Low Energy Yields): marley::EventFileReader Class Reference
marley::EventFileReader Class Reference
Object that parses MARLEY output files written in any of the available formats, except for ROOT format.
#include <EventFileReader.hh>
Public Member Functions
EventFileReader (const std::string &file_name)
double flux_averaged_xsec (bool natural_units=false)
Returns the flux-averaged total cross section used to produce the events in the file.
virtual bool next_event (marley::Event &ev)
Read the next MARLEY event record from the file.
virtual operator bool () const
Implicit boolean conversion allows the state of the input stream (or ROOT file) to be tested for readiness to read in another event.
EventFileReader & operator>> (marley::Event &ev)
Stream operator for reading in the next event.
Protected Member Functions
virtual bool deduce_file_format ()
Helper function that auto-detects which of the available output formats is appropriate for the requested file.
void ensure_initialized ()
This function should be called at the beginning of all public member functions of EventFileReader that interact with data in the file.
virtual void initialize ()
Prepares the file for reading the events.
Protected Attributes
std::string file_name_
Name of the file (with any needed path specification) to be read.
double flux_avg_tot_xs_ = 0.
Flux-averaged total cross section (MeV -2) used to produce the events in the file, or zero if that information is not included in a particular format.
OutputFile::Format format_
Format of the output file being read.
std::ifstream in_
Input stream used to read from textual output formats.
bool initialized_ = false
Flag that indicates whether initialize() has been called or not.
marley::JSON json_event_array_
Used to parse events from JSON-format files.
marley::JSON::JSONWrapper< std::deque< marley::JSON > > json_event_array_wrapper_
Used to iterate over events from JSON-format files.
std::deque< marley::JSON >::iterator json_event_iter_
Iterator to the next JSON event in json_event_array.
Detailed Description
Object that parses MARLEY output files written in any of the available formats, except for ROOT format.
For a version of this class that can also handle ROOT-format output files, see the RootEventFileReader class
Definition at line 34 of file EventFileReader.hh.
Member Function Documentation
ensure_initialized()
void marley::EventFileReader::ensure_initialized () protected
This function should be called at the beginning of all public member functions of EventFileReader that interact with data in the file.
It provides necessary initialization as a workaround to calling virtual functions in the constructor
Definition at line 223 of file EventFileReader.cc.
{
   if ( !initialized_ ) {
     if ( !this->deduce_file_format() ) throw marley::Error("Could not"
       " read MARLEY events from the file \"" + file_name_ + '\"');
     this->initialize();
     initialized_ = true;
   }
 }
flux_averaged_xsec()
double marley::EventFileReader::flux_averaged_xsec (bool natural_units = false)
Returns the flux-averaged total cross section used to produce the events in the file.
For file formats which do not include this information, this function will return zero
Parameters
[in] natural_units If true, then this function will return the flux-averaged total cross section in natural units (MeV -2). If false (default), then 10-42 cm2 will be used.
Definition at line 233 of file EventFileReader.cc.
{
   this->ensure_initialized();
   if ( natural_units ) return flux_avg_tot_xs_;
   double result = flux_avg_tot_xs_ * marley_utils::hbar_c2
     * marley_utils::fm2_to_minus40_cm2 * 1e2; // 10^{-42} cm^2
   return result;
 }
next_event()
bool marley::EventFileReader::next_event (marley::Event & ev) virtual
Read the next MARLEY event record from the file.
Parameters
[out] ev Reference to the object that will be filled with the next event record
Returns
True if reading the next event was successful, or false otherwise. This behavior is designed to be used as a while loop condition for iterating over events in the output file
Reimplemented in marley::RootEventFileReader.
Definition at line 160 of file EventFileReader.cc.
 {
   this->ensure_initialized();
   switch ( format_ ) {
     case marley::OutputFile::Format::ROOT:
       MARLEY_LOG_WARNING() << "Cannot read from ROOT file."
         << "Please use the marley::EventFileReader class and build"
         << " MARLEY with ROOT support.";
       return false;
       break;
     case marley::OutputFile::Format::ASCII:
       in_ >> ev;
       if ( in_ ) return true;
       break;
     case marley::OutputFile::Format::HEPEVT:
       if ( ev.read_hepevt(in_, &flux_avg_tot_xs_) ) return true;
       break;
     case marley::OutputFile::Format::JSON:
       ++json_event_iter_;
       if ( json_event_iter_ != json_event_array_wrapper_.end() ) {
         ev.from_json( *json_event_iter_ );
         return true;
       }
       break;
     default:
       throw marley::Error("Unrecognized file format encountered in"
         " marley::EventFileReader::next_event()");
   }
   ev = marley::Event();
   return false;
 }
References marley::Event::from_json().
Referenced by marley::RootEventFileReader::next_event(), and operator>>().
Member Data Documentation
format_
OutputFile::Format marley::EventFileReader::format_ protected
Format of the output file being read.
This format will be determined automatically by deduce_file_format() and does not need to be specified by the user
Definition at line 80 of file EventFileReader.hh.
Referenced by deduce_file_format(), and marley::RootEventFileReader::deduce_file_format().
initialized_
bool marley::EventFileReader::initialized_ = false protected
Flag that indicates whether initialize() has been called or not.
To avoid problems with using virtual functions in the constructor, we defer nearly all of the initialization to the first call to one of the other public member functions.
Definition at line 103 of file EventFileReader.hh.
The documentation for this class was generated from the following files:
/Users/gardiner/fooey/include/marley/EventFileReader.hh
/Users/gardiner/fooey/src/EventFileReader.cc