MARLEY (Model of Argon Reaction Low Energy Yields): marley::Level Class Reference
marley::Level Class Reference
A discrete nuclear energy level.
#include <Level.hh>
Public Member Functions
Level (double E, int twoJ, marley::Parity pi)
marley::Gamma & add_gamma (const marley::Gamma &gamma)
Add a new gamma-ray transition to this level.
marley::Gamma & add_gamma (double energy, double branching_ratio, marley::Level *end_lev=nullptr)
Add a new gamma-ray transition to this level.
void clear_gammas ()
Remove all gamma ray information from this level.
double energy () const
Get the excitation energy of this level (MeV)
std::vector< marley::Gamma > & gammas ()
Retrieve a reference to the vector of gamma rays owned by this level.
const std::vector< marley::Gamma > & gammas () const
Retrieve a const reference to the vector of gamma rays owned by this level.
bool has_gammas () const
marley::Parity parity () const
Get the level parity.
const marley::Gamma * sample_gamma (marley::Generator &gen)
Choose a gamma owned by this level randomly based on the relative intensities of all of the gammas.
void set_energy (double E)
Set the excitation energy of this level (MeV)
void set_parity (marley::Parity pi)
Set the level parity.
void set_twoJ (int twoJ)
Set two times the level spin.
std::string spin_parity_string () const
Returns the level spin-parity as a string.
int twoJ () const
Get two times the level spin.
Static Public Member Functions
template<typename It >
static marley::IteratorToPointerMember< It, double > make_energy_iterator (It it)
Convert an iterator that points to a marley::Level* (or a smart pointer to a marley::Level) into an iterator that points to the Level's energy_ member variable.
Detailed Description
A discrete nuclear energy level.
Definition at line 29 of file Level.hh.
Constructor & Destructor Documentation
Level()
marley::Level::Level (double E, int twoJ, marley::Parity pi)
Parameters
E excitation energy of this level (MeV)
twoJ two times the level spin
pi level parity
Definition at line 26 of file Level.cc.
                                                       : energy_(E),
   twoJ_(twoJ), parity_(pi) {}
Member Function Documentation
add_gamma() [1/2]
marley::Gamma & marley::Level::add_gamma (const marley::Gamma & gamma)
Add a new gamma-ray transition to this level.
Returns
a reference to the newly added gamma
Definition at line 42 of file Level.cc.
{
   // Update the vector of gamma objects
   gammas_.push_back(gamma);
   // Update the distribution for sampling gammas
   update_gamma_distribution();
   // Return a reference to the newly added gamma
   return gammas_.back();
 }
Referenced by marley::DecayScheme::read_from_stream().
add_gamma() [2/2]
marley::Gamma & marley::Level::add_gamma (double energy, double branching_ratio, marley::Level * end_lev = nullptr)
Add a new gamma-ray transition to this level.
Parameters
energy Gamma-ray energy (MeV)
branching_ratio Branching ratio for the new gamma-ray transition
end_lev Pointer to the level that absorbs this gamma
Returns
a reference to the newly added gamma
Definition at line 53 of file Level.cc.
 {
   // Update the vector of gamma objects
   gammas_.emplace_back(energy, branching_ratio, this, end_lev);
   // Update the distribution for sampling gammas
   update_gamma_distribution();
   // Return a reference to the newly added gamma
   return gammas_.back();
 }
has_gammas()
bool marley::Level::has_gammas () const inline
Returns
true if the level owns at least one Gamma object
Definition at line 133 of file Level.hh.
 { return !gammas_.empty(); }
make_energy_iterator()
template<typename It > marley::IteratorToPointerMember< It, double > marley::Level::make_energy_iterator (It it) inline static
Convert an iterator that points to a marley::Level* (or a smart pointer to a marley::Level) into an iterator that points to the Level's energy_ member variable.
This function is used by the DecayScheme class to keep the vector of std::unique_ptr<marley::Level> objects that it owns sorted in order of increasing excitation energy.
Definition at line 136 of file Level.hh.
   {
     return marley::IteratorToPointerMember<It, double>(it,
       &marley::Level::energy_);
   }
Referenced by marley::DecayScheme::level_lower_bound_index().
sample_gamma()
const marley::Gamma * marley::Level::sample_gamma (marley::Generator & gen)
Choose a gamma owned by this level randomly based on the relative intensities of all of the gammas.
Returns
a pointer to the selected Gamma object, or nullptr if the level doesn't have any gammas
Definition at line 29 of file Level.cc.
 {
   if (gammas_.empty()) return nullptr;
   else {
     // Get the index of the gamma to return by randomly sampling from the
     // discrete distribution gamma_dist using the standard marley_utils random
     // number generator.
     size_t g_index = gen.sample_from_distribution(gamma_dist_);
     // Return a pointer to the corresponding gamma
     return &(gammas_[g_index]);
   }
 }
References marley::Generator::sample_from_distribution().
Referenced by marley::DecayScheme::do_cascade().
The documentation for this class was generated from the following files:
/Users/gardiner/fooey/include/marley/Level.hh
/Users/gardiner/fooey/src/Level.cc