MARLEY (Model of Argon Reaction Low Energy Yields): marley::KoningDelarocheOpticalModel Class Reference
marley::KoningDelarocheOpticalModel Class Reference
Nuclear optical model for fragment emission calculations.
#include <KoningDelarocheOpticalModel.hh>
Public Member Functions
KoningDelarocheOpticalModel (int Z, int A, double step_size=DEFAULT_NUMEROV_STEP_SIZE_)
virtual std::complex< double > optical_model_potential (double r, double fragment_KE_lab, int fragment_pdg, int two_j, int l, int two_s, int target_charge=0) override
Calculate the optical model potential (including the Coulomb potential)
virtual double total_cross_section (double fragment_KE_lab, int fragment_pdg, int two_s, size_t l_max, int target_charge=0) override
Compute the energy-averaged total cross section (MeV -2) for a nuclear fragment projectile.
virtual double transmission_coefficient (double total_KE_CM, int fragment_pdg, int two_j, int l, int two_s, int target_charge=0) override
Calculate the transmission coefficient for a nuclear fragment.
Public Member Functions inherited from marley::OpticalModel
OpticalModel (int Z, int A)
int A () const
Get the mass number.
int Z () const
Get the atomic number.
Additional Inherited Members
Protected Attributes inherited from marley::OpticalModel
int A_
int Z_
Detailed Description
Nuclear optical model for fragment emission calculations.
This class implements the global optical model potential of A. J. Koning and J. P. Delaroche, Nucl. Phys. A 713 (2003) 231-310. Numerov's method is used to integrate the Schrödinger equation during transmission coefficient and cross section calculations.
Definition at line 37 of file KoningDelarocheOpticalModel.hh.
Constructor & Destructor Documentation
KoningDelarocheOpticalModel()
marley::KoningDelarocheOpticalModel::KoningDelarocheOpticalModel (int Z, int A, double step_size = DEFAULT_NUMEROV_STEP_SIZE_)
Parameters
Z Atomic number of the desired nuclide
A Mass number of the desired nuclide
step_size Step size (fm) to use for numerical integration of the Schrödinger equation
Definition at line 194 of file KoningDelarocheOpticalModel.cc.
                            : marley::OpticalModel(Z, A), step_size_(step_size)
 {
   const auto& mt = marley::MassTable::Instance();
   target_mass_ = mt.get_atomic_mass(Z, A);
   int N = A_ - Z_; // Neutron number
   double A_to_the_one_third = std::pow(A_, 1.0/3.0);
   // Initialize the spherical optical model parameters (see TALYS 1.6 manual)
   // Neutrons
   v1n = 59.30 - 21.0*(N - Z_)/A_ - 0.024*A_; // MeV
   v2n = 0.007228 - 1.48e-6*A_; // MeV^(-1)
   v3n = 1.994e-5 - 2.0e-8*A_; // MeV^(-2)
   v4n = 7e-9; // MeV^(-3)
   w1n = 12.195 + 0.0167*A_; // MeV
   w2n = 73.55 + 0.0795*A_; // MeV
   d1n = 16.0 - 16.0*(N - Z_)/A_; // MeV
   d2n = 0.0180 + 0.003802/(1 + std::exp((A_ - 156.)/8.0)); // MeV^(-1)
   d3n = 11.5; // MeV
   vso1n = 5.922 + 0.0030*A_; // MeV
   vso2n = 0.0040; // MeV^(-1)
   wso1n = -3.1; // MeV
   wso2n = 160.; // MeV
   Efn = -11.2814 + 0.02646*A_; // MeV
   Rvn = 1.3039*A_to_the_one_third - 0.4054; // fm
   avn = 0.6778 - 1.487e-4*A_; // fm
   Rdn = 1.3424*A_to_the_one_third
     - 0.01585*std::pow(A_to_the_one_third, 2); // fm
   adn = 0.5446 - 1.656e-4*A_; // fm
   Rso_n = 1.1854*A_to_the_one_third - 0.647; // fm
   aso_n = 0.59; // fm
   // Protons
   v1p = 59.30 + 21.0*(N - Z_)/A_ - 0.024*A_; // MeV
   v2p = 0.007067 + 4.23e-6*A_; // MeV^(-1)
   v3p = 1.729e-5 + 1.136e-8*A_; // MeV^(-2)
   v4p = v4n; // MeV^(-3)
   w1p = 14.667 + 0.009629*A_; // MeV
   w2p = w2n; // MeV
   d1p = 16.0 + 16.0*(N - Z_)/A_; // MeV
   d2p = d2n; // MeV^(-1)
   d3p = d3n; // MeV
   vso1p = vso1n; // MeV
   vso2p = vso2n; // MeV^(-1)
   wso1p = wso1n; // MeV
   wso2p = wso2n; // MeV
   Efp = -8.4075 + 0.01378*A_; // MeV
   Rvp = Rvn;
   avp = avn;
   Rdp = Rdn;
   adp = 0.5187 + 5.205e-4*A_; // fm
   Rso_p = Rso_n;
   aso_p = aso_n;
   Rc = 1.198*A_to_the_one_third + 0.697/A_to_the_one_third
     + 12.994*std::pow(A_to_the_one_third, -4); // fm
   Vcbar_p = 1.73 * Z_ / Rc; // MeV
 }
References marley::OpticalModel::A(), marley::MassTable::Instance(), and marley::OpticalModel::Z().
Member Function Documentation
optical_model_potential()
std::complex< double > marley::KoningDelarocheOpticalModel::optical_model_potential (double r, double fragment_KE_lab, int fragment_pdg, int two_j, int l, int two_s, int target_charge = 0) override virtual
Calculate the optical model potential (including the Coulomb potential)
Parameters
r Distance from nuclear center (fm)
fragment_KE_lab Fragment kinetic energy (MeV) in the lab frame
fragment_pdg PDG code for the nuclear fragment
two_j Two times the total angular momentum of the fragment
l Orbital angular momentum of the fragment
two_s Two times the spin of the fragment
target_charge Net charge of the target atom
Returns
Complex-valued optical model potential (MeV)
Todo:
TODO: find a better way of doing this!
Implements marley::OpticalModel.
Definition at line 25 of file KoningDelarocheOpticalModel.cc.
 {
   update_target_mass( target_charge );
   // The calculate_kinematic_variables() function will set the fragment_mass_
   // member variable, but we need that value in advance in order to provide the total
   // CM frame kinetic energy as input. To get around this, retrieve the fragment mass
   // directly from the mass table instead
   const auto& mt = marley::MassTable::Instance();
   double m_fragment = mt.get_particle_mass( fragment_pdg );
   double KE_tot_CM = std::max(0., marley_utils::real_sqrt(
     std::pow(target_mass_ + m_fragment, 2)
     + 2.*target_mass_*fragment_KE_lab) - m_fragment - target_mass_);
   calculate_kinematic_variables( KE_tot_CM, fragment_pdg );
   calculate_om_parameters(fragment_pdg, two_j, l, two_s);
   return omp(r);
 }
References marley::MassTable::Instance().
total_cross_section()
double marley::KoningDelarocheOpticalModel::total_cross_section (double fragment_KE_lab, int fragment_pdg, int two_s, size_t l_max, int target_charge = 0) override virtual
Compute the energy-averaged total cross section (MeV -2) for a nuclear fragment projectile.
The total cross section given here by the optical model may be directly compared to experiment. Expressions exist for the optical model elastic and reaction (absorption) cross sections, but these are hard to directly compare to the data because the absorption cross section includes the compound elastic channel.
For more details, see appendix A (especially equation A.12) of S. Gardiner, "Nuclear Effects in Neutrino Detection," PhD thesis, University of California, Davis, 2018. Note that we assume in this function that the target nucleus has zero spin (spherical optical model).
Parameters
fragment_KE_lab Lab-frame kinetic energy of the incident projectile (MeV)
fragment_pdg Projectile's PDG code
two_s Two times the spin of the projectile
l_max The maximum value of the orbital angular momentum quantum number \(\ell\) to include in the sum over S-matrix elements
target_charge Net charge of the target atom (used to adjust the atomic mass by the appropriate number of electron masses if the target is ionized)
Returns
Energy-averaged total scattering cross section (MeV -2)
Todo:
TODO: find a better way of doing this!
Implements marley::OpticalModel.
Definition at line 256 of file KoningDelarocheOpticalModel.cc.
 {
   update_target_mass( target_charge );
   // The calculate_kinematic_variables() function will set the fragment_mass_
   // member variable, but we need that value in advance in order to provide the total
   // CM frame kinetic energy as input. To get around this, retrieve the fragment mass
   // directly from the mass table instead
   const auto& mt = marley::MassTable::Instance();
   double m_fragment = mt.get_particle_mass( fragment_pdg );
   double KE_tot_CM = std::max(0., marley_utils::real_sqrt(
     std::pow(target_mass_ + m_fragment, 2)
     + 2.*target_mass_*fragment_KE_lab) - m_fragment - target_mass_);
   calculate_kinematic_variables( KE_tot_CM, fragment_pdg );
   double sum = 0.;
   for (size_t l = 0; l <= l_max; ++l) {
     int two_l = 2*l;
     for (int two_j = std::abs(two_l - two_s);
       two_j <= two_l + two_s; two_j += 2)
     {
       std::complex<double> S = s_matrix_element(fragment_pdg, two_j, l, two_s);
       sum += (two_j + 1) * (1 - S.real());
     }
   }
   // Compute the cross section in natural units (MeV^(-2))
   double xs = marley_utils::two_pi * sum / ((two_s + 1) * CM_frame_momentum_squared_);
   return xs;
 }
References marley::MassTable::Instance().
transmission_coefficient()
double marley::KoningDelarocheOpticalModel::transmission_coefficient (double total_KE_CM, int fragment_pdg, int two_j, int l, int two_s, int target_charge = 0) override virtual
Calculate the transmission coefficient for a nuclear fragment.
Parameters
total_KE_CM Total CM frame kinetic energy (MeV)
fragment_pdg PDG code of the fragment
two_j Two times the total angular momentum of the fragment
l Orbital angular momentum of the fragment
two_s Two times the spin of the fragment
target_charge Net charge of the target atom
Implements marley::OpticalModel.
Definition at line 292 of file KoningDelarocheOpticalModel.cc.
 {
   if ( total_KE_CM <= 0. ) return 0.;
   update_target_mass( target_charge );
   calculate_kinematic_variables( total_KE_CM, fragment_pdg );
   std::complex<double> S = s_matrix_element(fragment_pdg, two_j, l, two_s);
   // Guard against ±inf or NaN values that can occur in edge cases when the
   // Coulomb wavefunctions get huge, e.g., for low-energy alpha emission.
   // Numerical precision problems can lead to wrong answers, such as S == (inf,
   // 0) instead of the correct (1, 0).
   bool S_is_finite = std::isfinite( S.real() ) && std::isfinite( S.imag() );
   // If we have a ±inf or NaN in one of the components of S, then set the
   // transmission coefficient to zero
   if ( !S_is_finite ) return 0.;
   // To guard against numerical issues that can make the norm of the S-matrix
   // element creep above unity, explicitly enforce that it lies on the interval
   // [0, 1].
   // TODO: revisit this, perhaps add a warning message?
   double norm_S = std::norm(S);
   if ( norm_S < 0. || norm_S > 1.0000001 ) {
     MARLEY_LOG_DEBUG() << "Invalid S-matrix norm = " << norm_S << '\n';
   }
   norm_S = std::min(1., std::max(0., norm_S));
   // We can now compute the transmission coefficient in the usual way
   return 1.0 - norm_S;
 }
The documentation for this class was generated from the following files:
/home/sjg/GENIE/marley/include/marley/KoningDelarocheOpticalModel.hh
/home/sjg/GENIE/marley/src/KoningDelarocheOpticalModel.cc