MARLEY (Model of Argon Reaction Low Energy Yields): marley::Event Class Reference
marley::Event Class Reference
Container for ingoing and outgoing momentum 4-vectors from a reaction.
#include <Event.hh>
Public Member Functions
Event (const Event &other_event)
Copy constructor.
Event (const marley::Particle &a, const marley::Particle &b, const marley::Particle &c, const marley::Particle &d, double Ex, int twoJ, const marley::Parity &P)
Create a two-two scattering event.
Event (double Ex=0.)
Create an event with dummy particles.
Event (Event &&other_event)
Move constructor.
void add_final_particle (const marley::Particle &p)
Add a Particle to the vector of final particles.
void add_initial_particle (const marley::Particle &p)
Add a Particle to the vector of initial particles.
void clear ()
Deletes all particles from the event and resets the nuclear excitation energy to zero.
marley::Particle & ejectile ()
Get a non-const reference to the ejectile.
const marley::Particle & ejectile () const
Get a const reference to the ejectile.
double Ex () const
Get the excitation energy of the residue just after the initial two-body reaction.
const marley::Particle & final_particle (size_t idx) const
Returns a const reference to the final particle with the given index.
size_t final_particle_count () const
Returns the number of final particles in the Event.
void from_json (const marley::JSON &json)
Replace the existing event contents with those read from a JSON representation.
std::vector< marley::Particle * > & get_final_particles ()
Get a non-const reference to the vector of final particles.
const std::vector< marley::Particle * > & get_final_particles () const
Get a const reference to the vector of final particles.
std::vector< marley::Particle * > & get_initial_particles ()
Get a non-const reference to the vector of initial particles.
const std::vector< marley::Particle * > & get_initial_particles () const
Get a const reference to the vector of initial particles.
const marley::Particle & initial_particle (size_t idx) const
Returns a const reference to the initial particle with the given index.
size_t initial_particle_count () const
Returns the number of initial particles in the Event.
Event & operator= (const Event &other_event)
Copy assignment operator.
Event & operator= (Event &&other_event)
Move assignment operator.
marley::Parity parity () const
Get the intrinsic parity of the residue just after the initial two-body reaction.
void print (std::ostream &out) const
Print this event to a std::ostream.
void print_human_readable (std::ostream &out, int num=-1) const
Print this event to a std::ostream in an annotated format easily readable by humans.
marley::Particle & projectile ()
Get a non-const reference to the projectile.
const marley::Particle & projectile () const
Get a const reference to the projectile.
void read (std::istream &in)
Read in this event from a std::istream. Any previous contents of this event will be deleted.
bool read_hepevt (std::istream &in, double *flux_avg_tot_xsec=nullptr)
Read in this event from a std::istream, assuming it will appear there in HEPEVT format. Any previous contents of this event will be deleted.
marley::Particle & residue ()
Get a non-const reference to the residue.
const marley::Particle & residue () const
Get a const reference to the residue.
marley::Particle & target ()
Get a non-const reference to the target.
const marley::Particle & target () const
Get a const reference to the target.
marley::JSON to_json () const
Create a JSON representation of this event.
int twoJ () const
Get two times the spin of the residue just after the initial two-body reaction.
void write_hepevt (size_t event_num, double flux_avg_tot_xsec, std::ostream &out) const
Write a HEPEVT record for this event to a std::ostream. Use the spacetime origin (t = 0 mm/c, x = 0 mm, y = 0 mm, z = 0 mm) as the initial position 4-vector for all particles.
Protected Member Functions
void delete_particles ()
Deletes all owned Particle objects and clears the vectors of initial and final particles.
void dump_hepevt_particle (const marley::Particle &p, std::ostream &os, int status, int jmohep1=0, int jmohep2=0) const
Helper function for write_hepevt()
Protected Attributes
double Ex_
Excitation energy (MeV) of the residue immediately after the two-two scattering reaction.
std::vector< marley::Particle * > final_particles_
Vector of pointers to each of the final state particles.
std::vector< marley::Particle * > initial_particles_
Vector of pointers to each of the initial state particles.
Parity parity_
The parity of the residue immediately after the two-two scattering reaction.
int twoJ_
Two times the spin of the residue immediately after the two-two scattering reaction.
Detailed Description
Container for ingoing and outgoing momentum 4-vectors from a reaction.
For a two-two scattering reaction a + b → c + d, this class calls the ingoing particles the projectile (a) and target (b). The outgoing particles are called the ejectile (c) and residue (d). If the residue is a composite particle (e.g., a nucleus), then the class member Ex_ stores its excitation energy just after the two-two reaction occurred. After MARLEY simulates its de-excitation, the residue Particle object will be in its ground state, and the final_particles_ member of this class will include Particle objects representing the de-excitation products.
Note
This class manually manages memory (using the “rule of 5”) for the Particle objects that it owns. A better implementation from a modern C++ perspective would be to use vectors of std::unique_ptr<marley::Particle> objects and let those manage the memory (i.e., use the “rule of zero”). This design choice was made to ensure compatibility with ROOT 5, which cannot generate dictionaries for C++11 classes like std::unique_ptr.
Definition at line 66 of file Event.hh.
Constructor & Destructor Documentation
Event()
marley::Event::Event (const marley::Particle & a, const marley::Particle & b, const marley::Particle & c, const marley::Particle & d, double Ex, int twoJ, const marley::Parity & P)
Create a two-two scattering event.
Parameters
a the projectile
b the target
c the ejectile
d the residue
Ex residue excitation energy (MeV) just after the two-two reaction
Definition at line 67 of file Event.cc.
   : initial_particles_{new marley::Particle(a), new marley::Particle(b)},
   final_particles_{new marley::Particle(c), new marley::Particle(d)},
   Ex_(Ex), twoJ_(twoJ), parity_(P) {}
Member Function Documentation
dump_hepevt_particle()
void marley::Event::dump_hepevt_particle (const marley::Particle & p, std::ostream & os, int status, int jmohep1 = 0, int jmohep2 = 0) const protected
Helper function for write_hepevt()
Parameters
p Particle to write to the HEPEVT record
os std::ostream being written to
status Integer status code to use for this particle in the HEPEVT output
jmohep1 Index of the first mother for this particle (used only for a "MARLEY info" dummy particle at the moment)
jmohep2 Index of the second mother for this particle (used only for a "MARLEY info" dummy particle at the moment)
Definition at line 294 of file Event.cc.
 {
   // Print the status code to begin the particle entry in the HEPEVT record
   os << status << ' ';
   // TODO: improve this entry to give the user more control over the vertex
   // location and to reflect the parent-daughter relationships between
   // particles.
   // Convert from MARLEY natural units (MeV) to GeV for the HEPEVT format
   os << p.pdg_code() << ' ' << jmohep1 << ' ' << jmohep2 << " 0 0 "
     << p.px() / GEV_TO_MEV << ' ' << p.py() / GEV_TO_MEV
     << ' ' << p.pz() / GEV_TO_MEV << ' ' << p.total_energy() / GEV_TO_MEV
     << ' ' << p.mass() / GEV_TO_MEV
     // The spacetime origin is currently used as the initial position 4-vector
     // for all particles
     << " 0. 0. 0. 0." << '\n';
 }
References marley::Particle::mass(), marley::Particle::pdg_code(), marley::Particle::px(), marley::Particle::py(), marley::Particle::pz(), and marley::Particle::total_energy().
final_particle()
const marley::Particle & marley::Event::final_particle (size_t idx) const inline
Returns a const reference to the final particle with the given index.
Parameters
[in] idx Index of the desired particle
Exceptions
std::out_of_range if idx is greater than or equal to the size of the vector of final particles
Definition at line 303 of file Event.hh.
{
     return *final_particles_.at( idx );
   }
References final_particles_.
initial_particle()
const marley::Particle & marley::Event::initial_particle (size_t idx) const inline
Returns a const reference to the initial particle with the given index.
Parameters
[in] idx Index of the desired particle
Exceptions
std::out_of_range if idx is greater than or equal to the size of the vector of initial particles
Definition at line 299 of file Event.hh.
{
     return *initial_particles_.at( idx );
   }
References initial_particles_.
print()
void marley::Event::print (std::ostream & out) const
Print this event to a std::ostream.
Parameters
out The std::ostream to which this event will be written
Definition at line 226 of file Event.cc.
{
   // Use an temporary ostringstream object so that we can ensure all
   // floating-point values are output with full precision without disturbing
   // the user's settings in the "out" stream.
   std::ostringstream temp;
   temp << std::scientific;
   temp.precision(std::numeric_limits<double>::max_digits10);
   temp << initial_particles_.size() << ' ' << final_particles_.size()
     << ' ' << Ex_ << ' ' << twoJ_ << ' ' << parity_ << '\n';
   for (const auto i : initial_particles_) temp << *i << '\n';
   for (const auto f : final_particles_) temp << *f << '\n';
   out << temp.str();
 }
print_human_readable()
void marley::Event::print_human_readable (std::ostream & out, int num = -1) const
Print this event to a std::ostream in an annotated format easily readable by humans.
Parameters
out The std::ostream to which this event will be written
num An optional event number that will be printed with the rest of the event. If num is negative, then it will be skipped.
Definition at line 641 of file Event.cc.
{
   out << "\n*** MARLEY Event ";
   if ( num >= 0 ) out << num << ' ';
   out << "has " << this->get_initial_particles().size()
     << " initial particles and " << this->get_final_particles().size()
     << " final particles. ***" << '\n';
   int twoJ = this->twoJ();
   bool twoJ_is_odd = ( twoJ % 2 == 1 );
   out << "The residual nucleus initially had excitation energy "
     << this->Ex() << " MeV and spin-parity ";
   if ( twoJ_is_odd ) out << twoJ << "/2";
   else out << twoJ / 2;
   out << this->parity() << '\n';
   out << "Initial particles" << '\n';
   marley::Particle* p = NULL;
   for (size_t i = 0u; i < this->get_initial_particles().size(); ++i) {
     print_particle_info( out, *this->get_initial_particles().at(i) );
   }
   out << "Final particles" << '\n';
   for (size_t i = 0u; i < this->get_final_particles().size(); ++i) {
     print_particle_info( out, *this->get_final_particles().at(i) );
   }
 }
read()
void marley::Event::read (std::istream & in)
Read in this event from a std::istream. Any previous contents of this event will be deleted.
Parameters
in The std::istream from which this event will be read
Definition at line 243 of file Event.cc.
{
   this->clear();
   int num_initial;
   int num_final;
   in >> num_initial >> num_final >> Ex_ >> twoJ_ >> parity_;
   // If reading the event header line failed for some
   // reason, just return without trying to do anything else.
   if ( !in ) return;
   // If we have invalid numbers of particles in either the initial or final
   // state (there need to be at least two in each and we can't fill memory when
   // allocating space for them) then complain by throwing an error
   if ( num_initial < 2 || static_cast<size_t>(num_initial)
     > initial_particles_.max_size() )
   {
     throw marley::Error("Invalid number of initial state particles ("
       + std::to_string(num_initial) + ") encountered in marley::Event::read()");
   }
   else if ( num_final < 2 || static_cast<size_t>(num_final)
     > final_particles_.max_size() )
   {
     throw marley::Error("Invalid number of final state particles ("
       + std::to_string(num_final) + ") encountered in marley::Event::read()");
   }
   initial_particles_.resize( num_initial );
   final_particles_.resize( num_final );
   for (int i = 0; i < num_initial; ++i) {
     marley::Particle* p = new marley::Particle;
     in >> *p;
     if ( !in ) throw marley::Error("Parse error while reading initial"
       " particle #" + std::to_string(i) + " from an ASCII-format event"
       " record");
     initial_particles_.at(i) = p;
   }
   for (int f = 0; f < num_final; ++f) {
     marley::Particle* p = new marley::Particle;
     in >> *p;
     if ( !in ) throw marley::Error("Parse error while reading final"
       " particle #" + std::to_string(f) + " from an ASCII-format event"
       " record");
     final_particles_.at(f) = p;
   }
 }
read_hepevt()
bool marley::Event::read_hepevt (std::istream & in, double * flux_avg_tot_xsec = nullptr)
Read in this event from a std::istream, assuming it will appear there in HEPEVT format. Any previous contents of this event will be deleted.
A marley::Error will be thrown if
There are not exactly two particles in the event with the status code HEPEVT_INITIAL_STATE_STATUS_CODE
There is not exactly one particle with status code HEPEVT_INITIAL_STATE_STATUS_CODE that is an ion (a particle for which marley_utils::is_ion() returns true)
More than one lepton (a particle for which marley_utils::is_lepton() returns true) appears in the event with status code HEPEVT_FINAL_STATE_STATUS_CODE
Zero of the particles with status code HEPEVT_FINAL_STATE_STATUS_CODE are ions
Returns
True if the input stream was in a good state after attempting to read in the full HEPEVT record, or false otherwise. This behavior is designed to enable the return value of this function to be used as a while loop condition when reading in multiple HEPEVT records from an input stream. If the return value is false, the event object contents will have been cleared by this function.
Definition at line 380 of file Event.cc.
 {
   // If flux_avg_tot_xsec is not null, then clear any previous value there
   // before continuing. It will be loaded with a new value below if we
   // find a dummy particle encoding extra MARLEY-specific information in
   // the input HEPEVT record.
   if ( flux_avg_tot_xsec ) *flux_avg_tot_xsec = 0.;
   // Remove any pre-existing contents in this event
   this->clear();
   // Check that the event contains exactly two initial-state particles
   size_t initial_state_particles = 0u;
   // Check that one of the initial-state particles is an atom (ion)
   size_t initial_state_ions = 0u;
   // Check that the event contains exactly one final-state lepton
   size_t final_state_leptons = 0u;
   // Check that the event contains at least one final-state ion
   size_t final_state_ions = 0u;
   // Initial indices of the final lepton and largest final ion (as judged
   // by the mass number A) in the final_particles_
   // vector. These will be used below to move them into the correct order.
   size_t final_lepton_idx = 0u;
   size_t largest_final_ion_idx = 0u;
   int largest_A = 0;
   int event_num; // HEPEVT event number (ignored)
   int num_particles; // Total number of particles stored in the event
   in >> event_num  >> num_particles;
   // If reading the first line failed for some
   // reason, just return without trying to do anything else.
   if ( !in ) return false;
   // If the number of particles in the event is negative or extremely
   // huge (so that it would overload memory) then throw a marley::Error
   if ( num_particles < 0 || static_cast<size_t>(num_particles)
     > initial_particles_.max_size() )
   {
     throw marley::Error("Invalid number of particles ("
       + std::to_string(num_particles) + ") encountered in marley::"
       "Event::read_hepevt()");
   }
   // Dummy variables used to skip HEPEVT fields that MARLEY doesn't
   // care about (e.g., the particle production vertex 4-position)
   int dummy_int;
   double dummy_double;
   // Fields that we do care about
   double Etot, px, py, pz, M;
   int status_code, pdg, jmohep1, jmohep2;
   for ( int p = 0; p < num_particles; ++p ) {
     in >> status_code >> pdg >> jmohep1 >> jmohep2;
     // Skip the JDAHEP1 and JDAHEP2 fields (daughter indices)
     for ( int j = 0; j < 2; ++j ) in >> dummy_int;
     // Read in the particle 4-momentum and mass.
     in >> px >> py >> pz >> Etot >> M;
     // Skip the VHEP1 through VHEP4 fields (production vertex 4-position)
     for ( int j = 0; j < 4; ++j ) in >> dummy_double;
     if ( !in ) throw marley::Error("Parse error while reading  particle #"
       + std::to_string(p) + " from a HEPEVT-format event record");
     // If the particle has this status code, it is a dummy particle that
     // contains MARLEY-specific information
     if ( status_code == HEPEVT_MARLEY_INFO_STATUS_CODE ) {
       // The dummy particle total energy stores the nuclear excitation energy.
       // This value can be reconstructed (with some effort) from the
       // particle four-vectors, but just storing it is a lot easier.
       Ex_ = Etot;
       // The dummy particle mass stores the flux-averaged total cross section.
       // If the user passed something other than a nullptr as the
       // flux_avg_tot_xsec argument to this function, then load it
       // with this value, which is not normally stored in the marley::Event
       // itself.
       if ( flux_avg_tot_xsec ) *flux_avg_tot_xsec = M;
       // The JMOHEP1 field contains two times the residue spin immediately
       // following the initial two-two scattering reaction
       twoJ_ = jmohep1;
       // The JMOHEP2 field contains an integer representation of the residue
       // parity immediately following the initial two-two scattering reaction
       parity_ = jmohep2;
     }
     // If the particle has a status code other than the two used by
     // MARLEY, then don't bother to record the particle in the event object
     if ( status_code != HEPEVT_INITIAL_STATE_STATUS_CODE
       && status_code != HEPEVT_FINAL_STATE_STATUS_CODE ) continue;
     // Convert the particle 4-momentum components and mass from GeV (used in
     // the HEPEVT format) to MARLEY natural units (MeV)
     px *= GEV_TO_MEV;
     py *= GEV_TO_MEV;
     pz *= GEV_TO_MEV;
     Etot *= GEV_TO_MEV;
     M *= GEV_TO_MEV;
     // We already checked that the particle has a status code recognized
     // by MARLEY above, so store it in the event object in the appropriate
     // place.
     if ( status_code == HEPEVT_INITIAL_STATE_STATUS_CODE ) {
       initial_particles_.push_back(
         new marley::Particle(pdg, Etot, px, py, pz, M) );
       ++initial_state_particles;
       if ( marley_utils::is_ion(pdg) ) ++initial_state_ions;
     }
     else {
       // status_code == HEPEVT_FINAL_STATE_STATUS_CODE
       final_particles_.push_back(
         new marley::Particle(pdg, Etot, px, py, pz, M) );
       if ( marley_utils::is_lepton(pdg) ) {
         ++final_state_leptons;
         final_lepton_idx = final_particles_.size() - 1;
       }
       if ( marley_utils::is_ion(pdg) ) {
         ++final_state_ions;
         // Update the index of the largest final ion
         int A = marley_utils::get_particle_A( pdg ); // mass number
         if ( A > largest_A ) {
           largest_A = A;
           largest_final_ion_idx = final_particles_.size() - 1;
         }
       }
     }
   }
   // Check that the event satisfies the criteria needed for a reasonable
   // marley::Event
   if ( initial_state_particles != 2u ) throw marley::Error(
     std::to_string(initial_state_particles) + " initial-state particles"
     " encountered while reading HEPEVT input");
   else if ( initial_state_ions != 1u ) throw marley::Error("Multiple"
     " initial-state ions encountered while reading HEPEVT input");
   else if ( final_state_leptons != 1u ) throw marley::Error("Multiple"
     " final-state leptons encountered while reading HEPEVT input");
   else if ( final_state_ions < 1u ) throw marley::Error("Zero"
     " final-state ions encountered while reading HEPEVT input");
   // Reorder (if needed) the initial particle list to ensure that the target
   // (the initial atom) appears in the correct position. This is required
   // because marley::Event objects rely on the ordering of the
   // initial_particles_ array to allow easy retrieval of the projectile and
   // target.
   auto target_iter = initial_particles_.begin() + TARGET_INDEX;
   if ( !marley_utils::is_ion( (*target_iter)->pdg_code() ) ) {
     auto begin_ip = initial_particles_.begin();
     std::iter_swap( begin_ip, begin_ip + 1 );
   }
   // Play the same sort of game with the final particles. This will ensure that
   // the ejectile and residue are stored in the correct places.
   auto begin_fp = final_particles_.begin();
   if ( final_lepton_idx != EJECTILE_INDEX ) {
     std::iter_swap( begin_fp + EJECTILE_INDEX, begin_fp + final_lepton_idx );
   }
   if ( largest_final_ion_idx != RESIDUE_INDEX ) {
     std::iter_swap( begin_fp + RESIDUE_INDEX, begin_fp + largest_final_ion_idx );
   }
   // The marley::Particle constructor that we used above assumes that all ion
   // PDG codes passed to it represent fully ionized particles. Here we will
   // override this behavior and assume instead that the target atom has
   // zero net charge in the initial state.
   this->target().set_charge( 0 );
   // Determine the correct ionization state immediately following the prompt
   // 2-->2 scattering reaction. Do this by assuming that the target atom is
   // neutral (see above). This implies that the final ion charge must be equal
   // and opposite to that of the final lepton.
   int Qf_ion = -this->ejectile().charge();
   // Get the nuclear residue net electric charge by summing all final-state
   // ions besides the residue itself. The difference between this sum and the
   // pre-de-excitation ion charge is the charge that should be used.
   int sum_Q_final_ions = 0;
   for ( size_t f = 0u; f < final_particles_.size(); ++f ) {
     if ( f == RESIDUE_INDEX ) continue; // skip the residue
     const auto& fp = final_particles_.at( f );
     int pdg_f = fp->pdg_code();
     if ( marley_utils::is_ion(pdg_f) ) sum_Q_final_ions += fp->charge();
   }
   this->residue().set_charge( Qf_ion - sum_Q_final_ions );
   // Everything was read in successfully. We're done!
   return true;
 }
Referenced by marley::EventFileReader::deduce_file_format().
write_hepevt()
void marley::Event::write_hepevt (size_t event_num, double flux_avg_tot_xsec, std::ostream & out) const
Write a HEPEVT record for this event to a std::ostream. Use the spacetime origin (t = 0 mm/c, x = 0 mm, y = 0 mm, z = 0 mm) as the initial position 4-vector for all particles.
Parameters
[in] flux_avg_tot_xsec The flux-averaged total reaction cross section (MeV -2) to include in the output HEPEVT record
[in] event_num The event number to use in the output HEPEVT record
[out] The std::ostream to which the HEPEVT record will be written
Todo:
Alter marley::Event::write_hepevt() so that the user can specify a vertex position 4-vector to use.
Definition at line 313 of file Event.cc.
 {
   // Use an temporary ostringstream object so that we can ensure all
   // floating-point values are output with full precision without disturbing
   // the user's settings in the "out" stream.
   std::ostringstream temp;
   temp.precision( std::numeric_limits<double>::max_digits10 );
   temp << std::scientific;
   // Create a dummy particle that encodes extra MARLEY-specific information in
   // the HEPEVT format. Preserve MARLEY natural units for these quantities
   // (MeV) by pre-multiplying by the conversion factor used in
   // dump_hepevt_particle()
   marley::Particle dummy_particle;
   dummy_particle.set_total_energy( Ex_ * GEV_TO_MEV );
   dummy_particle.set_mass( flux_avg_tot_xsec * GEV_TO_MEV );
   // Add one to the total particle count so that our dummy particle will be
   // included correctly
   size_t num_particles = 1 + initial_particles_.size()
     + final_particles_.size();
   // Write the HEPEVT header line to the event record
   temp << event_num  << ' ' << num_particles << '\n';
   // Write the initial particles to the event record
   for (const auto i : initial_particles_) dump_hepevt_particle(*i, temp,
     HEPEVT_INITIAL_STATE_STATUS_CODE);
   // Write our dummy particle to the event record
   // We use the jmohep1 slot to record the twoJ_ data member and the jmohep2
   // slot to record the parity_ data member (both as integers)
   dump_hepevt_particle( dummy_particle, temp, HEPEVT_MARLEY_INFO_STATUS_CODE,
     twoJ_, static_cast<int>(parity_) );
   // Write the final particles to the event record
   for (const auto f : final_particles_) dump_hepevt_particle(*f, temp,
     HEPEVT_FINAL_STATE_STATUS_CODE);
   // Output the finished HEPEVT format event to the "out" stream
   out << temp.str();
 }
References marley::Particle::set_mass(), and marley::Particle::set_total_energy().
Member Data Documentation
Ex_
double marley::Event::Ex_ protected
Excitation energy (MeV) of the residue immediately after the two-two scattering reaction.
Note
The Ex_ class member is always zero for residues that have no excited states.
Definition at line 249 of file Event.hh.
Referenced by Ex(), and operator=().
The documentation for this class was generated from the following files:
/home/sjg/GENIE/marley/include/marley/Event.hh
/home/sjg/GENIE/marley/src/Event.cc