MARLEY (Model of Argon Reaction Low Energy Yields): marley::ExitChannel Class Reference
marley::ExitChannel Class Reference abstract
Abstract base class for compound nucleus de-excitation channels.
#include <ExitChannel.hh>
Public Member Functions
ExitChannel ()=default
ExitChannel (int pdgi, int qi, double Exi, int twoJi, marley::Parity Pi, double rho_i, marley::StructureDatabase &sdb)
virtual void do_decay (double &Exf, int &two_Jf, marley::Parity &Pf, const marley::Particle &compound_nucleus, marley::Particle &emitted_particle, marley::Particle &residual_nucleus, marley::Generator &gen) const =0
Simulates a nuclear decay into this channel.
virtual bool emits_fragment () const =0
Returns true if this channel involves fragment emission or false if it involves gamma-ray emission.
virtual int emitted_particle_pdg () const =0
Returns the PDG code for the particle (gamma-ray or nuclear fragment) emitted by decays into this ExitChannel.
virtual int final_nucleus_pdg () const =0
Returns the PDG code for the final nucleus.
virtual bool is_continuum () const =0
Returns true if this channel accesses the particle-unbound continuum of nuclear levels or false otherwise.
double width () const
Get the total decay width into this channel (MeV)
Static Public Member Functions
template<typename It >
static marley::IteratorToPointerMember< It, double > make_width_iterator (It it)
Convert an iterator that points to an ExitChannel object into an iterator to the ExitChannel's width_ member variable.
Protected Member Functions
virtual void compute_total_width ()=0
virtual void prepare_products (const marley::Particle &compound_nucleus, marley::Particle &emitted_particle, marley::Particle &residual_nucleus, double Exf, marley::Generator &gen) const
Helper function that prepares Particle objects representing the products of the two-body decay.
Protected Attributes
double Exi_
Initial nuclear excitation energy \(E_x \) (MeV)
double one_over_two_pi_rho_i_
int pdgi_
PDG code for the initial nucleus.
marley::Parity Pi_
Initial nuclear parity \(\Pi \).
int qi_
marley::StructureDatabase * sdb_
StructureDatabase to use in calculations.
int twoJi_
Two times the initial nuclear spin \(J \).
double width_
Total decay width into this channel (MeV)
Detailed Description
Abstract base class for compound nucleus de-excitation channels.
Definition at line 36 of file ExitChannel.hh.
Constructor & Destructor Documentation
ExitChannel() [1/2]
marley::ExitChannel::ExitChannel () default
Note
This line keeps old versions (4.9.3) of GCC happy
ExitChannel() [2/2]
marley::ExitChannel::ExitChannel (int pdgi, int qi, double Exi, int twoJi, marley::Parity Pi, double rho_i, marley::StructureDatabase & sdb) inline
Parameters
pdgi PDG code for the initial nucleus
qi Net charge (in units of the elementary charge) of the initial atom or ion
Exi Initial nuclear excitation energy \(E_x \) (MeV)
twoJi Two times the initial nuclear spin \(J \)
Pi Initial nuclear parity \(\Pi \)
rho_i Initial nuclear level density \(\rho(E_x, J, \Pi) \) in the vicinity of the initial level (MeV -1). This value will be used to compute an overall normalization factor for decay widths in this exit channel.
sdb Reference to the StructureDatabase that will be used in decay width calculations by this ExitChannel object
Definition at line 55 of file ExitChannel.hh.
                                                      : pdgi_( pdgi ),
         qi_( qi ), Exi_( Exi ), twoJi_( twoJi ), Pi_( Pi ), sdb_( &sdb )
       {
         one_over_two_pi_rho_i_ = std::pow( 2. * marley_utils::pi * rho_i, -1 );
       }
References one_over_two_pi_rho_i_.
Member Function Documentation
compute_total_width()
virtual void marley::ExitChannel::compute_total_width () protected pure virtual
Helper function that initializes the width_ member variable upon construction
Implemented in marley::GammaDiscreteExitChannel, marley::FragmentDiscreteExitChannel, and marley::ContinuumExitChannel.
Referenced by marley::FragmentContinuumExitChannel::FragmentContinuumExitChannel(), marley::FragmentDiscreteExitChannel::FragmentDiscreteExitChannel(), marley::GammaContinuumExitChannel::GammaContinuumExitChannel(), and marley::GammaDiscreteExitChannel::GammaDiscreteExitChannel().
do_decay()
virtual void marley::ExitChannel::do_decay (double & Exf, int & two_Jf, marley::Parity & Pf, const marley::Particle & compound_nucleus, marley::Particle & emitted_particle, marley::Particle & residual_nucleus, marley::Generator & gen) const pure virtual
Simulates a nuclear decay into this channel.
Parameters
[out] Exf The final nuclear excitation energy
[out] two_Jf Two times the final nuclear spin
[out] Pf The final nuclear parity
[in] compound_nucleus Particle object representing the initial nucleus
[out] emitted_particle Particle emitted in the de-excitation
[out] residual_nucleus Final-state nucleus after particle emission
gen Generator to use for random sampling
Implemented in marley::ContinuumExitChannel, and marley::DiscreteExitChannel.
make_width_iterator()
template<typename It > static marley::IteratorToPointerMember<It, double> marley::ExitChannel::make_width_iterator (It it) inline static
Convert an iterator that points to an ExitChannel object into an iterator to the ExitChannel's width_ member variable.
This is used to load a std::discrete_distribution with decay widths for sampling without redundant storage.
Definition at line 92 of file ExitChannel.hh.
       {
         return marley::IteratorToPointerMember<It,
           double>(it, &marley::ExitChannel::width_);
       }
References width_.
Referenced by marley::HauserFeshbachDecay::sample_exit_channel().
prepare_products()
void marley::ExitChannel::prepare_products (const marley::Particle & compound_nucleus, marley::Particle & emitted_particle, marley::Particle & residual_nucleus, double Exf, marley::Generator & gen) const protected virtual
Helper function that prepares Particle objects representing the products of the two-body decay.
Parameters
[out] compound_nucleus Particle object representing the initial nucleus
[out] emitted_particle Particle emitted in the binary decay
[out] residual_nucleus Particle representing the daughter nucleus
[in] Exf Excitation energy of the daughter nucleus
gen Generator to use for random sampling
Definition at line 380 of file ExitChannel.cc.
 {
   const auto& mt = marley::MassTable::Instance();
   int ep_pdg = this->emitted_particle_pdg();
   double ep_mass = mt.get_particle_mass( ep_pdg );
   emitted_particle = marley::Particle( ep_pdg, ep_mass );
   // Proton number of the emitted particle
   int ep_Z = marley_utils::get_particle_Z( ep_pdg );
   // Final ion charge after particle emission
   int qf = qi_ - ep_Z;
   double me = mt.get_particle_mass( marley_utils::ELECTRON );
   int remnant_pdg = this->final_nucleus_pdg();
   // Approximate the ground state mass of the ion formed when the fragment is
   // emitted by subtracting qf electron masses from the atomic mass for the
   // final nuclide.
   double Mfgs_ion = mt.get_atomic_mass( remnant_pdg ) - qf*me;
   residual_nucleus = marley::Particle( remnant_pdg, Mfgs_ion + Exf, qf );
   // Now that the PDG codes, masses, and net charges of the binary decay
   // products have been set, choose a direction for the emitted particle.
   // TODO: Consider changing this to a more realistic model instead of
   // isotropic emissions.
   double cos_theta_emitted_particle
     = gen.uniform_random_double( -1., 1., true );
   double phi_emitted_particle
     = gen.uniform_random_double( 0., marley_utils::two_pi, false );
   // Handle the kinematics calculations for this decay. Load the
   // final-state particle objects with their full 4-momenta.
   marley_kinematics::two_body_decay( compound_nucleus, emitted_particle,
     residual_nucleus, cos_theta_emitted_particle, phi_emitted_particle );
 }
References marley::MassTable::Instance(), and marley::Generator::uniform_random_double().
Member Data Documentation
one_over_two_pi_rho_i_
double marley::ExitChannel::one_over_two_pi_rho_i_ protected
Normalization factor needed so that the decay widths have correct units
This factor is equal to \(\left[ 2\pi\rho(E_x, J, \Pi) \right]^{-1} \) where \(\rho\) is the initial nuclear level density (MeV -1) in the vicinity of the initial nuclear level. This level has excitation energy \(E_x \), total spin \(J \), and parity \(\Pi \).
Definition at line 149 of file ExitChannel.hh.
Referenced by ExitChannel().
qi_
int marley::ExitChannel::qi_ protected
Net charge (in units of the elementary charge) of the initial atom or ion
Definition at line 132 of file ExitChannel.hh.
The documentation for this class was generated from the following files:
/home/sjg/GENIE/marley/include/marley/ExitChannel.hh
/home/sjg/GENIE/marley/src/ExitChannel.cc