MARLEY (Model of Argon Reaction Low Energy Yields): marley::Particle Class Reference
marley::Particle Class Reference
Momentum four-vector for a simulated particle.
#include <Particle.hh>
Public Member Functions
Particle (int pdg_code, double E, double px, double py, double pz, double m)
Particle (int pdg_code, double E, double px, double py, double pz, double m, int q)
Particle (int pdg_code, double m)
Particle (int pdg_code, double m, int q)
Particle (int pdg_code, double px, double py, double pz, double m)
Particle (int pdg_code, double px, double py, double pz, double m, int q)
double charge () const
Get the particle's charge in units of the proton charge.
void clear ()
Resets all data members to zero.
void from_json (const marley::JSON &json)
Replaces the existing object contents with new ones loaded from a JSON representation of a Particle.
double kinetic_energy () const
Get the particle's kinetic energy (MeV)
double mass () const
Get the particle's mass (MeV)
double momentum_magnitude () const
Get the magnitude of the particle's 3-momentum (MeV)
int pdg_code () const
Get the Particle Data Group code for this particle.
void print (std::ostream &out) const
Print information about this particle to a std::ostream.
double px () const
Get the x component of the particle's 3-momentum (MeV)
double py () const
Get the y component of the particle's 3-momentum (MeV)
double pz () const
Get the z component of the particle's 3-momentum (MeV)
void read (std::istream &in)
Read in this particle from a std::istream. Any previous contents of this particle will be deleted.
void set_charge (int q)
Set the particle's charge.
void set_mass (double m)
Set the particle's mass.
void set_px (double px)
Set the x component of the particle's 3-momentum.
void set_py (double py)
Set the y component of the particle's 3-momentum.
void set_pz (double pz)
Set the z component of the particle's 3-momentum.
void set_total_energy (double Etot)
Set the particle's total energy.
marley::JSON to_json () const
Create a JSON representation of this Particle.
double total_energy () const
Get the particle's total energy (MeV)
Protected Attributes
int charge_ = 0
Electric charge (net charge in the case of atoms) expressed as an integer multiple of the proton charge.
double four_momentum_ [4]
momentum 4-vector for this particle (MeV)
double mass_ = 0.
mass (MeV)
int pdg_code_ = 0
Particle Data Group code identifying this particle
Detailed Description
Momentum four-vector for a simulated particle.
Definition at line 32 of file Particle.hh.
Constructor & Destructor Documentation
Particle() [1/6]
marley::Particle::Particle (int pdg_code, double m)
Parameters
pdg_code Particle Data Group code
m mass (MeV)
Definition at line 59 of file Particle.cc.
   : four_momentum_{0., 0., 0., 0.}, pdg_code_(pdg_code), mass_(m),
   charge_(marley_utils::get_particle_charge(pdg_code)) {}
Particle() [2/6]
marley::Particle::Particle (int pdg_code, double m, int q)
Parameters
pdg_code Particle Data Group code
m mass (MeV)
q charge in units of the proton charge
Definition at line 63 of file Particle.cc.
   : four_momentum_{ m, 0., 0., 0. }, pdg_code_(pdg_code), mass_(m),
   charge_(q) {}
Particle() [3/6]
marley::Particle::Particle (int pdg_code, double px, double py, double pz, double m)
Parameters
pdg_code Particle Data Group code
px 3-momentum x component (MeV)
py 3-momentum y component (MeV)
pz 3-momentum z component (MeV)
m mass (MeV)
Definition at line 67 of file Particle.cc.
             : four_momentum_{ 0., px, py, pz }, pdg_code_(pdg_code), mass_(m),
   charge_(marley_utils::get_particle_charge(pdg_code))
 {
   double E = std::sqrt(std::pow(m, 2) + std::pow(px, 2) + std::pow(py, 2)
     + std::pow(pz, 2));
   four_momentum_[0] = E;
 }
References four_momentum_, px(), py(), and pz().
Particle() [4/6]
marley::Particle::Particle (int pdg_code, double px, double py, double pz, double m, int q)
Parameters
pdg_code Particle Data Group code
px 3-momentum x component (MeV)
py 3-momentum y component (MeV)
pz 3-momentum z component (MeV)
m mass (MeV)
q charge in units of the proton charge
Definition at line 76 of file Particle.cc.
                    : four_momentum_{ 0., px, py, pz }, pdg_code_(pdg_code),
   mass_(m), charge_(q)
 {
   double E = std::sqrt(std::pow(m, 2) + std::pow(px, 2) + std::pow(py, 2)
     + std::pow(pz, 2));
   four_momentum_[0] = E;
 }
References four_momentum_, px(), py(), and pz().
Particle() [5/6]
marley::Particle::Particle (int pdg_code, double E, double px, double py, double pz, double m)
Parameters
pdg_code Particle Data Group code
E total energy (MeV)
px 3-momentum x component (MeV)
py 3-momentum y component (MeV)
pz 3-momentum z component (MeV)
m mass (MeV)
Definition at line 85 of file Particle.cc.
                                   : four_momentum_{ E, px, py, pz },
   pdg_code_(pdg_code), mass_(m),
   charge_(marley_utils::get_particle_charge(pdg_code)) {}
Particle() [6/6]
marley::Particle::Particle (int pdg_code, double E, double px, double py, double pz, double m, int q)
Parameters
pdg_code Particle Data Group code
E total energy (MeV)
px 3-momentum x component (MeV)
py 3-momentum y component (MeV)
pz 3-momentum z component (MeV)
m mass (MeV)
q charge in units of the proton charge
Definition at line 90 of file Particle.cc.
                                          : four_momentum_{ E, px, py, pz },
   pdg_code_(pdg_code), mass_(m), charge_(q) {}
Member Function Documentation
print()
void marley::Particle::print (std::ostream & out) const
Print information about this particle to a std::ostream.
Note
Although marley::Event::print() guarantees full precision for stream output, this function does not if it is called directly. If you need to serialize individual particle objects to text and read them back in again, either use an output stream with the proper precision set in advance (at least std::numeric_limits<double>::max_digits10), or consider using JSON input/output.
Definition at line 109 of file Particle.cc.
{
   out << pdg_code_ << ' ' << four_momentum_[0] << ' ' << four_momentum_[1]
     << ' ' << four_momentum_[2] << ' ' << four_momentum_[3]
     << ' ' << mass_ << ' ' << charge_;
 }
set_charge()
void marley::Particle::set_charge (int q) inline
Set the particle's charge.
Parameters
q charge in units of the proton charge
Definition at line 195 of file Particle.hh.
 { charge_ = q; }
References charge_.
set_mass()
void marley::Particle::set_mass (double m) inline
Set the particle's mass.
Parameters
m mass (MeV)
Definition at line 177 of file Particle.hh.
 { mass_ = m; }
References mass_.
Referenced by marley::Event::write_hepevt().
set_px()
void marley::Particle::set_px (double px) inline
Set the x component of the particle's 3-momentum.
Parameters
px 3-momentum x component (MeV)
Definition at line 184 of file Particle.hh.
 { four_momentum_[1] = px; }
References four_momentum_, and px().
Referenced by marley::RotationMatrix::rotate_particle_inplace().
set_py()
void marley::Particle::set_py (double py) inline
Set the y component of the particle's 3-momentum.
Parameters
py 3-momentum y component (MeV)
Definition at line 187 of file Particle.hh.
 { four_momentum_[2] = py; }
References four_momentum_, and py().
Referenced by marley::RotationMatrix::rotate_particle_inplace().
set_pz()
void marley::Particle::set_pz (double pz) inline
Set the z component of the particle's 3-momentum.
Parameters
pz 3-momentum z component (MeV)
Definition at line 190 of file Particle.hh.
 { four_momentum_[3] = pz; }
References four_momentum_, and pz().
Referenced by marley::RotationMatrix::rotate_particle_inplace().
set_total_energy()
void marley::Particle::set_total_energy (double Etot) inline
Set the particle's total energy.
Parameters
Etot total energy (MeV)
Definition at line 180 of file Particle.hh.
     { four_momentum_[0] = Etot; }
References four_momentum_.
Referenced by marley::Event::write_hepevt().
Member Data Documentation
charge_
int marley::Particle::charge_ = 0 protected
Electric charge (net charge in the case of atoms) expressed as an integer multiple of the proton charge.
This class member allows a marley::Particle to represent an atom or ion. The charge_ data member was added because the 2014 PDG codes do not include a prescription for representing ionization states of atoms.
Todo:
Add error handling for cases where a marley::Particle is constructed with a charge that is inappropriate.
Definition at line 172 of file Particle.hh.
Referenced by charge(), and set_charge().
four_momentum_
double marley::Particle::four_momentum_[4] protected
momentum 4-vector for this particle (MeV)
The order of the components is (E, px, py, pz)
Note
This should be replaced by the more modern std::array<double, 4>. However, we use a C-style array here to allow ROOT 5, which is widely used but not C++11 compliant, to generate dictionaries for this class for TFile I/O. It'd be nice to include a default initializer here (say, = {0., 0., 0., 0.}), but ROOT 5 can't handle that either.
Definition at line 154 of file Particle.hh.
Referenced by Particle(), px(), py(), pz(), set_px(), set_py(), set_pz(), set_total_energy(), and total_energy().
pdg_code_
int marley::Particle::pdg_code_ = 0 protected
Particle Data Group code identifying this particle
See the full list of PDG codes for details.
Definition at line 159 of file Particle.hh.
Referenced by pdg_code().
The documentation for this class was generated from the following files:
/home/sjg/GENIE/marley/include/marley/Particle.hh
/home/sjg/GENIE/marley/src/Particle.cc